### ISSUE TITLE
Ignore line length convention for readme

### ISSUE THREAD

**Issue by cg-cnu** [exercism/python#1150]
Hey guys,

So, this is a minor annoyance am facing while using the readme. Lot of other language repos are also facing this. Since am actively using python thought I will ask for opinion here. 

`readme.md` files are written with a strict line length in most of the cases. You can look at the raw file [here](https://raw.githubusercontent.com/exercism/python/master/exercises/simple-cipher/README.md) to get an idea.

When I clone and try to open in an editor. I usually prefer to keep the code on one side and the readme on another. Since its a lot of text its breaking up more than necessary because of the newlines.
![image](https://user-images.githubusercontent.com/2767425/34467236-550d59d2-ef11-11e7-8163-716f738c133f.png)

Can we ignore the line length convention in the readme files ? Hope I made myself clear. Let me know your opinions. Will be happy to do a pr fixing those.

Happy new year 🙂

**Comment by cmccandless** [comment]
README files are generated from content in exercism/problem-specifications using exercism/configlet, so any issue with their content or format will probably belong at one of those. Since you're here already, I will add my two cents:

The 80 character limit is a common coming style convention that allows for the most consistent readability across most editors and viewers. It is uncommon to abandon a standard for a single use case (unless it breaks usability and no work around can be found). In your case, I suggest the Preview Markdown action for VSCode. This will render the README in a new tab, eliminating your code wrapping issue.

**Comment by cg-cnu** [comment]
Hey @cmccandless You are absolutely right. It not necessary to change the convention, stupid me, completely forgot about the handy markdown preview in vscode.

Thanks for correcting me. Have a happy new year 🙂
