### ISSUE TITLE
Perfect-Numbers: Skip computation-intensive tests

### ISSUE THREAD

**Issue by pheanex** [exercism/python#1155]
When automating running the tests for all exercises i noticed that two tests for the exercise "perfect-numers" are quite slow/computational intensive, namely "test_sixth_perfect_number" and "test_seventh_perfect_number".
I'd vote to skip/remove them because:
* Canonical data from upstream does not include them
* They do not provide any more coverage (we already have "test_large_perfect_number")
* It wastes compute resources and effectively prevents running automated&unmodified tests

Opinions? Especially @behrtam , @emerali and @cmccandless

**Comment by emerali** [comment]
I'm checking the most recent relevant PR that I can find ([here](https://travis-ci.org/exercism/python/builds/315488087)), and based on the test runs of this exercise on Travis CI, it doesn't seem like it takes a whole lot of time overall (always less than 0.1s, from what I saw), so this feels like a sort of micro-optimization to me. 

Though to be fair, there isn't really much to lose, and it'll probably take less than a minute to fix :stuck_out_tongue: 

I don't have any strong feeling towards this, so I'll just leave it up to the actual project maintainers.

**Comment by cmccandless** [comment]
There has been some talk here recently about track-specific tests. The gist of it is whether to 
- treat them as any other test
- skip them by default
- remove them entirely

I believe we already have a precedent for option 2, but can't look it up at the moment. If you can find a precedent in another exercise, I'm willing to approve skipping them here as well.

**Comment by pheanex** [comment]
I could not find the precedent you mentioned. I'd suggest to put this on hold until we find the precedent or we come to an agreement on how to handle track-specific tests for this and all other exercises.
=> I'd also be okay with skipping them by default

**Comment by cmccandless** [comment]
@pheanex [`largest-series-product`](https://github.com/exercism/python/blob/a64db4638323cd4fa4fb2857faf0b5d3329dfb71/exercises/largest-series-product/largest_series_product_test.py#L69) is the precedent I was thinking of. This exercise actually has an [explicit exception](https://github.com/exercism/python/blob/a64db4638323cd4fa4fb2857faf0b5d3329dfb71/test/check-exercises.py#L13) to allow Travis-CI to skip exercises marked `@unittest.skip()`, whereas that line is ignored for other exercises (per #1081). The decision was made because, unlike the situations @emerali observed, this test's runtime was on the order of seconds, not milliseconds, causing noticeable delay in Travis builds.

My personal thoughts on this issue are somewhat in alignment with your original statement: if the tests do not provide additional coverage, they only waste resources. There are some track-specific tests which test properties not tested at all by canonical data (see [`secret-handshake`](https://github.com/exercism/python/blob/bc66616109e18c45eb169a9460d7e9389e934ea1/exercises/secret-handshake/secret_handshake_test.py#L48-L77)); I would be open to discussing those as well.

**Comment by cmccandless** [comment]
Thinking about this more, I am of the opinion that if a track-specific test does not provide additional coverage, it should be removed. If the test does provide additional coverage, then a PR should be submitted to problem-specifications to make it canonical.
