### ISSUE TITLE
help wanted! My code is wrongly failing! :( reverse_string

### ISSUE THREAD

**Issue by matthewgoldring** [exercism/python#1177]
Is this even the correct place to put this?!

Anyway, challenge 3. Completed surprisingly quickly by me and worked when I tested it myself.
Ran it through the tester and failed everything!!! Why?! 

Newbie here...please help.

def reverse(reverse_me):
    '''
    str ---> str

    '''
    new_word = ''
    for letter in reverse_me:
        new_word = letter + new_word
    print (new_word)

**Comment by cmccandless** [comment]
If you are struggling with an exercise, the best thing to do is to submit your incomplete solution (i.e. `exercism submit reverse_string.py`), then write a comment on the submission on Exercism.io (the exact URL of your submission should be in the output of `exercism submit`) requesting assistance.

However, since you're already here: your solution fails because it doesn't return anything; it just prints it.
