### ISSUE TITLE
Is the markdown exercise supposed to come with a solution?

### ISSUE THREAD

**Issue by mandel01** [exercism/python#1694]
When I downloaded the `markdown` exercise, I was surprised that it came with a [full solution](https://github.com/exercism/python/blob/master/exercises/markdown/markdown.py). Was this intentional? If not, I can offer a PR to fix it.

**Comment by cmccandless** [comment]
Yes, this is intentional. From the [exercise README](https://github.com/exercism/python/blob/master/exercises/markdown/README.md):

> The markdown exercise is a refactoring exercise. There is code that parses a given string with Markdown syntax and returns the associated HTML for that string. Even though this code is confusingly written and hard to follow, somehow it works and all the tests are passing! Your challenge is to re-write this code to make it easier to read and maintain while still making sure that all the tests keep passing.

> It would be helpful if you made notes of what you did in your refactoring in comments so reviewers can see that, but it isn't strictly necessary. The most important thing is to make the code better!

As a refactoring exercise, a fully functional solution is provided. This solution, however, will be poorly written and/or inefficient. Unlike standard exercises, the unit tests in this exercise serve to help students ensure that their refactoring does not break functionality.

**Comment by mandel01** [comment]
I don't think I read the README... my mistake!! Thanks for your work on the project.
