### ISSUE TITLE
high-scores: incorrect solution can pass the tests

### ISSUE THREAD

**Issue by ali1234** [exercism/python#1745]
Consider the following partial solution to this problem:

```
class HighScores(object):
    def __init__(self, scores):
        self.scores = scores

    def latest(self):
        return self.scores[-1]

    def personal_best(self):
        self.scores.sort()
        return self.scores[-1]
```

This will pass the tests for the functions it implements. However, if latest is called after calling personal_best, it can give the wrong answer. The current tests do not check for this situation.

**Comment by cmccandless** [comment]
This issue has come up before in #1735.

Currently, side effect testing is outside the scope of this exercise. There is a discussion [here](https://github.com/exercism/problem-specifications/pull/1486) to include such tests, but I would like to wait and see the consensus there before adding these tests here.

Another solution discussed in #1744 would be to convert this track's implementation to use stand-alone functions rather than a class instance, which might make things more clear to students anyway.

**Comment by simmol** [comment]
PR #1764 will be merged soon that will make the exercise simpler (using separate functions).
