### ISSUE TITLE
tree-building: exercise already completed

### ISSUE THREAD

**Issue by jrom99** [exercism/python#1746]
Sorry if I'm posting this on the wrong place, but the side exercise Tree Building on Python Track is already done after being downloaded for the first time.
![image](https://user-images.githubusercontent.com/47498278/56095108-c93cbf00-5eaf-11e9-98f3-e0f7b09b9a5e.png)
![image](https://user-images.githubusercontent.com/47498278/56095111-dbb6f880-5eaf-11e9-959e-582a427ef213.png)
![image](https://user-images.githubusercontent.com/47498278/56095118-ed989b80-5eaf-11e9-8823-6c430fb2bc04.png)

**Comment by cmccandless** [comment]
Hi!

According to the exercise description (in your first screenshot), `tree-building` is a refactoring exercise. This means that, instead of simply implementing a solution yourself, your task is to *improve* an existing solution. This can be anything from removing redundant code to rewriting the solution entirely.

So yes, as you observed, a passing solution is delivered upon first download, but this is by design.

**Comment by jrom99** [comment]
Hi,

I see... Thank you very much! So I had misundestood the description, it also explains many things about that confusing piece of code.
