### ISSUE TITLE
[React]: Add /Review Test Template and Review and Test Exercise

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1976]
## Task
Create a test template file for `react`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `react-add-test-template`
    - Run: `git checkout -b react-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/react/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py react`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by beatorizu** [comment]
Hey, I would like to try this issue too :D

**Comment by yawpitch** [comment]
@beatorizu have fun with it, we welcome a PR.

**Comment by BethanyG** [comment]
Noting here:  90% of this work has been completed in PR #2096.  However, there has been **a lot** of changes since that PR was submitted, so the exercise, the specifications, and the generated tests need to be reviewed to make sure everything would still work with the template.  Leaving this issue open as a reminder that the review work needs to be completed, and at if all possible, we should resurrect the PR and get it to a state where it can be merged and used.

**Comment by BethanyG** [comment]
Closing this as the work was reviewed, adjusted and submitted.
