### ISSUE TITLE
hello-world: code fails the test locally but passes the uploader

### ISSUE THREAD

**Issue by bhagerty** [exercism/python#2117]
I assume that Exercism should reject uploaded code if that code would fail the local test. But this `hello-world.py` code passes if uploaded but fails the local test:

```python
def hello():
    print("Hello, World!")

hello()
```

As a newbie, it took me quite a while to figure out why it was failing the test locally—it fails because this function doesn't actually "return a value" when run, it just prints a string and returns `None`. So to pass the test locally, I had to write:

```python
def hello():
    return("Hello, World!")

print(hello())
```

I have two suggestions: (1) ensure that the uploader and the local test file are doing the same test so that a user either passes both or fails both; and (2) consider, in the instructions, making it clearer that the exercise's goal (have the program _return a value_ of "Hello, World!") is not the same thing as having the program simply _print or display_ the string "Hello, World!". 

I have not submitted this as a pull request because I don't know how to get at the tests in the uploader and because changing the instructions for "Hello, World!" might have to be done across exercises (if you agree with me).

**Comment by cmccandless** [comment]
The uploader doesn't run any user code at all. Automated tests are a work in progress, and are not yet deployed.

This is the excerpt from the [exercise README]:(https://github.com/exercism/python/blob/master/exercises/hello-world/README.md)
```
The objectives are simple:

- Write a function that returns the string "Hello, World!".
- Run the test suite and make sure that it succeeds.
- Submit your solution and check it at the website.
```

These instructions should be perfectly clear; functions, return values, string are all common terms across different languages.

@yawpitch, you have any input here? I'm not sure there's a next step here.

**Comment by bhagerty** [comment]
Thanks for the response @cmccandless. To you and @yawpitch, based on your response, I would say that this text in the README is confusing: `Submit your solution and check it at the website.` This text implies, at least to me (and I am a pretty normal reader), that _the website_ is going to check it, i.e., that automated tests are happening. Apparently you would read the phrase differently, to mean "submit your solution, then manually check it at the website" (though _against what_ the reader should check it would still not be clear from this: against other folks' solutions?).  But I think that my reading, which infers that the checking happens as part of the website submission, is actually more natural. 

So I would probably say something different, such as: `Submit your solution. You may then check it manually against other solutions if you like.`

As for the phrase `returns the string,` I understand that this wording is transparent to an experienced programmer, and I did eventually figure it out even though I'm inexperienced. But given that lots of other tutorials for beginners teach them to do something like simply write "Hello World" to output—rather than to write a function whose return value is "Hello World"—I don't think that the instruction is as clear as it could or should be. After all, I was confused at first. So for that phrase, I would instead write:

`Write a function whose return value is the string "Hello, World!".`

This phrasing makes it entirely clear that `return` is being used technically, not colloquially (because colloquially, you could say that `print("Hello, World!")` in some sense "returns" the string "Hello, World!" because it displays the string on your screen. 

You certainly don't have to change anything if you don't want to. But my feedback is some evidence of how a normal, fairly inexperienced person _might actually read_ the instructions, and it doesn't seem to be the way that you _expect them_ to read the instructions. In other words, while the instructions may be "perfectly clear" to you, they weren't to me. If they had been, I wouldn't have taken the time to comment here. Now maybe I'm reading these "perfectly clear" instructions wrong because I'm an idiot—but I'm pretty sure I'm not an idiot, and I'm pretty sure that it's possible to make the instructions clearer. 

Thanks again for the quick response and your careful consideration of my comments. I'm just trying to help you make Exercism better.

**Comment by yawpitch** [comment]
I agree with @bhagerty on the first point, “Submit your solution and check it at the website.” can be read as there being some sort of check mechanism on the website, either automated or manually initiated. However even saying “manually check it” or “check it manually” is ambiguous and implies a mechanism for manual testing. The actual objective meant to be communicated here is to submit the solution and then return to the website for further instructions. The student is already supposed to have passed the tests locally (see the prior objective), which would imply that the submitted solution need not be “checked” by or on the website, as it’s already a verified solution. Thus I’d suggest this be changed to “Run `exercism submit hello.py` and follow the link provided back to the website”. That said such a change would need to be made in the exercism/problem-specifications repo, as that’s where that copy actually originates. If you want to submit a PR there and ping me on here when you’ve done so I’ll be happy to review it.

That said I’m afraid I cannot agree that changes are necessary to address the second point; yes, “function that returns the string” is not as explicit as “function whose return value is the string”, but that ambiguity is in fact part of the challenge... we _want_ someone to, perhaps, try the “normal” (and, frankly, useless) approach of printing to stdout and for them to be surprised by the fact the test fails. That way they learn the significant difference between `print` and `return`.

We expressly do not wish to mimic “beginner” sites / books / classes that often teach `print` and `input` as programming, when in fact real-world professional programming only very rarely involves either of those tools.

Thus we want to state the exercise with some ambiguity and not point the student directly at the `return` statement for a reason: most students experienced enough in either programming or Python to get benefit from exercism will either already understand the implication or be able to figure it out for themselves and pass the test locally, so it’s either obvious to them or a useful learning exercise. If we “give away” the solution by being more explicit it’s not as valuable to the student who _doesn’t_ pass the tests locally the first time round.

Now, I do appreciate that might be frustrating, but exercism isn’t really targeted at people who are completely new to programming, so much as they are completely new to a specific programming language. We’re continuing to try and make the startup experience on the Python track a little more beginner-programmer friendly — and hopefully there will be some more progress on that over the next months — but this change would, I think, actually make their lives harder in the long run.

**Comment by bhagerty** [comment]
@yawpitch Thanks for the thoughtful response. I'll submit a PR on the first issue.

On the second issue, I understand the value of challenging a learner. As it happens, I don't think that this particular challenge is a good one. And consider that you and @cmccandless are defending it with contradictory rationales: (1) per @cmccandless, no change is needed because it is "perfectly clear," i.e., _unambiguous_; (2) per you, no change is needed  because it is _deliberately ambiguous_ and therefore productively challenging. The existence of two offered yet contradictory justifications is a good clue that something is amiss.

Also note that my proposed change (`whose return value is the string`) is not actually as directive as "point[ing] the student directly at the `return` statement," which you object to. It's just a clearer way of saying "that returns the string." The learner still has to know (or figure out) that the `return` statement is how you `return the string` or (equivalently but more clearly) set a `return value [that] is the string`. 

Exercism is a very useful site, and I appreciate the philosophy. I think my suggestion would improve it and wouldn't sacrifice any important values. If I haven't persuaded you, I'll just have to learn how to be more persuasive.

**Comment by yawpitch** [comment]
I'm afraid I'm not persuaded -- and am not likely to be -- but allow me to make unambiguous why.

Regarding this `return` line in particular there really is no contradiction in our rationales; the existing statement is used across all the tracks on exercism and is "perfectly clear" -- meaning not "absolutely and rigorously unambiguous" but "immediately and readily cognizable" -- _to the site's targeted audience_; the learning challenges presented to that audience as they start to pick up a new (and, usually, second or third) language are:

1. How do I create a string in this language?
2. How do I return a value in this language for test validation?

Because that audience, whom we expect to have at least _some_ programming experience, already knows that programming languages must have an in-built capacity for working with textual data and some means of giving a meaningful result back to the caller for further processing. The _specific_ answer to those challenges is _very_ different from language to language:

1. Python has two different "string" types and a `return` keyword.
2. Haskell has (at last glance) 5 different commonly-used types for handling textual data and uses implicit returns (their `return` function is for something quite different).
3. In Bash you actually _do_ "return" a string by writing it to stdout, because the only "return value" that Bash knows is the process exit code.

In yet other languages you'll "return" by writing to a specific CPU register or handing back a pointer to a memory address. In some very new orchestration languages you'd make a PUT call to a RPC / HTTP endpoint ... given all of that the notion of "set a return value that is a string" isn't necessarily sensible to all of those -- or to people coming to Python from them -- while the notion of a returning / giving back a specific string / piece of text, broadly, is.

So the intentional ambiguity, on our part, is indeed in prodding the user to recognize those challenges and to begin thinking about how to address them. That provocation is both warranted and clear, and no we don't want to "give away the ghost" by providing an overly explicit, especially language-specific, answer. For our primary audience there's no need for this particular phrase to be any more explicit than it already is.

Further, when it comes to those at the fringes or outside of that audience, we've got a bit of a filtering problem ... the simple truth is that anyone who _cannot_ make it past `hello-world` without us resolving the ambiguity in this phrase more clearly is, to be perfectly frank, not sufficiently prepared for the exercises that will follow, and will overwhelm us if we lower the bar much further. We're very much _not_ trying to teach Python to the completely new, utterly first-time programmer, so we require anyone who is coming at it from that fresh a perspective to demonstrate sufficient initiative that they can download the files, run the tests locally at the command line, update the file(s) as required until they can get the tests to pass, and then upload their solution without handholding ... that's the minimum effort and skillset threshold we need met before our mentors begin to spend their -- entirely volunteered -- time trying to help the prospective student.

You've responded to our provocation and demonstrated that initiative by getting this far ... that's wonderful, because it means the site is working for you, even if it's been frustrating. I very much appreciate the effort you're attempting to put into helping the community, we need that sort of help. However I'm also aware of what's going on "behind the scenes" as we move towards rolling out more changes that are meant to address the issues of complete newbies while also keeping maintainer / mentor workloads sustainable, and I hope that you can appreciate that @cmccandless and I know where the energy and time of maintainers needs to be focussed ... which is, gently but firmly, _NOT_ on working to make `hello-world` any more accessible than it already is.

All that said please do ping this thread when you submit a PR on the "check" copy.

**Comment by bhagerty** [comment]
Thanks @yawpitch . The explanation as to how different languages handle a similar situation is very helpful, as is the idea that creating some kind of a hurdle here is a feature, not a bug. Thanks for the explanation. It makes sense.
