### ISSUE TITLE
Non-existent control_flow tag

### ISSUE THREAD

**Issue by bsoyka** [exercism/python#2143]
The `go-counting`, `two-bucket`, and `spiral-matrix` exercises are all marked with the `control_flow` tag, which doesn't exist (not listed here: <https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt>).

I'm happy to make a pull request to fix this, but I'm not sure if it should be replaced or just removed. Thoughts?
<sub>[View in Slack](https://exercism-team.slack.com/archives/CASLGCCSZ/p1574693921051900)</sub>

**Comment by yawpitch** [comment]
The TOPICS.txt doesn’t represent a complete and definitive database of all possible valid tags; it’s merely a set of suggested topics for a new track being implemented, thus there’s no requirement on the basis of that file to either add the tag there or to consider deleting it from our exercises.

That said, the tag is quite vague and I’m not even certain it applies to the `spiral-matrix` at all, since neither conditionals or exceptions are used in the example solution and, arguably, the only control flow in it is the obvious one inherent to no-branch imperative flow.

So the original basis isn’t supported, but I’m happy to debate whether or not we should retire it entirely, or remove / replace it on an exercise by exercise basis.
