### ISSUE TITLE
grep: Use unittest.mock for testing

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#2147]
unittest.mock was not used originally because it was not available in Python 2.7. Since we've dropped support for Python 2.7, we can use the correct module for this now.

Work on this should be postponed until #2106 has been merged.

**Comment by beatorizu** [comment]
I would like to help with this

**Comment by AnAccountForReportingBugs** [comment]
I have the necessary mock setup. My problem is that I am having difficulty wrapping my head around the template engine. If anyone would like to assist, I attached a copy of the grep_test.py file.

**Comment by yawpitch** [comment]
@AnAccountForReportingBugs don't really have time at the moment to go through it blow by blow, but adding your changes to the template was relatively simple, and hopefully the diff in #2184 will help with Jinja2.  I did modify the KeyError fallback, yours had a lurking NameError but also we want a loud error rather than falling back on builtins.open.

**Comment by AnAccountForReportingBugs** [comment]
Thanks, what you did was very helpful by allowing me to see them side-by-side. I copied the behavior from the old system but agree yours is better. Much more explicit that way.  I also added a comment to the PR to fix the Travis failures.

Nice catch on the name error. I missed that trying to get the signatures to match the patching function. Lets also not mention the other subtle bug I made there....
