### ISSUE TITLE
clock: test that self is not modified by __add__()

### ISSUE THREAD

**Issue by roadfoodr** [exercism/python#2153]
The mentor notes for Clock (I am told) instruct mentors to check that `__add__()` does not modify `self`.  This makes sense: you wouldn't expect, for example, `clock2 = clock1 + 3` to modify `clock1` as a side-effect.

However, the test suite does not check for self-modification and I propose to add a test for this.  Moreover, [the example solution](https://github.com/exercism/python/blob/master/exercises/clock/example.py) does modify `self` and should also be changed to be consistent with the mentor notes.

Lastly, the instruction "You should be able to add and subtract minutes to it" could be intrepreted by students as intent that addition actually should modify the clock itself ("it").  This could be clarified with a more specific reference to the `+` and `-` operators being overridden.  (Aside: this instruction and the example solution are possibly artifacts from a previous version of the exercise, which involved an `add()` method rather than overriding `+`.)

If there is consensus around desired behavior here, I can submit a PR updating the test suite, example solution, and instructions.  These would be divergences from the canonical exercises; I'd appreciate a pointer to examples from other solutions where there are Python-specific divergences that I can use as a model.

**Comment by yawpitch** [comment]
At the moment we don't state, in the copy the student sees, any specific preference for an "immutable" implementation of `Clock` vs a mutable one ... this is because:

1. the two concepts haven't really been introduced earlier in the track
2. creating an _actually_ immutable type in Python is _hard_ (arguably, without resort to writing a C extension, it's impossible)
2. such a preference is, essentially, arbitrary, even if for a more experienced programmer there's a more "obvious" choice

For instance if you're modeling a bunch of wall clocks that need to be started in relationship to each other then immutability feels natural, but if what you're modeling is a wristwatch that you might wind forward or backwards at most a couple of times a year, or a bomb timer that may be set once and then only decrement, mutability becomes a more sensible fit.

Instead we've left the issue of mutability up to the student and focused on giving them an extremely simplistic introduction to basic operator overloading. Since we're introducing that overloading in a non-natural and _very_ cursory form -- we're allowing addition of a non-same-type but haven't touched on whether or not such an operation should be commutative -- it's been left up to the mentor to bring up these issues, rather than try and state a specific course through the copy and tests of the exercise.

Personally I'd rather see a PR re-writing the mentor notes -- which, BTW, are [here](https://github.com/exercism/website-copy/blob/master/tracks/python/exercises/clock/mentoring.md) -- as there's a lot of room for improvement there and a more general discussion of immutability / mutability and things like why the student might want to add all three of `__add__`, `__radd__`, and `__iadd__` would help the mentors help the students along to a greater degree than forcing the students towards a specific preferred implementation using the tests will help them.

**Comment by roadfoodr** [comment]
Fair enough, but let me clarify that my suggestion is focused on the behavior of the `+` operator -- a separate issue from the mutability of the `Clock` class itself.  In other words, my point can be restated as the question "should our introduction to operator overloading require students to consider why side-effects of an operator could be problematic?"

**Comment by yawpitch** [comment]
The conversation with the mentor is the most appropriate place for that consideration to occur. If we incorporate it into the tests we _aren’t_ having a conversation, we’re dictating a specific “preferred” implementation.

In this case the example.py is mutable because a mutable approach is _fine_ for the task at hand. It isn’t _ideal_, nor is it necessarily the most idiomatic approach to the problem, but a great many of our exercises are designed to be implementable in numerous ways... the tests represent a _minimally functional implementation_, they do not represent an ideal one.

So yes, a conversation about side effects is valuable, and that’s why it’s mentioned — very briefly — in the mentor’s notes, but adding tests to verify that mutation isn’t occurring is a step too far. Fleshing our the mentor notes is a great idea, but trying to mold the tests or copy towards a specific implementation isn’t necessary or, arguably, desirable.
