### ISSUE TITLE
[sgf-parsing] fix escaped characters test

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#2176]
Running the tests for `sgf-parsing` throws a DeprecationWarning related to an invalid escape sequence. This is due to the `\]` inclusions in the test string, which really should be `\\]` to work correctly.

Now from the canonical data we are getting `'(;A[\\]b\\nc\\nd\\t\\te \\n\\]])'`, but by the time it's rendered into the _test.py it's become `"(;A[\]b\nc\nd\t\te \n\]])"`, leading to the aforementioned warning.

To fix this we'd seemingly need to flag the literal as raw _before_ parsing the json file, or we'd need to manually correct for improperly escaped non-control characters.

Unfortunately we cannot just render the strings with "r" in front of them in the Jinja template, as that ends up turning `\n` into two characters, `\\` and `n`.

Open to ideas.

**Comment by cmccandless** [comment]
Can we just do this?
```Jinja2
input_string = '{{ case["input"]["encoded"] | replace("\\]", "\\\\]") }}'
```

**Comment by yawpitch** [comment]
You can certainly try it ... I tried a few different bits of tomfoolery with forcing the template to generate raw strings and that sure as hell didn't work.

**Comment by cmccandless** [comment]
The above suggestion works on my machine. If that's an acceptable solution, I'll PR it.

**Comment by yawpitch** [comment]
PR away.

**Comment by cmccandless** [comment]
So... that solved for ``\]`', but not `'\n'. The tests still pass, but... not a full solution.

**Comment by yawpitch** [comment]
Yeah ... methinks it may require a fairly complex re.sub.

**Comment by AnAccountForReportingBugs** [comment]
Here is my thought python defines the [valid backslash escapes](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) and jinja2 supports [custom filters](https://jinja.palletsprojects.com/en/2.10.x/api/#custom-filters).  Together, I think your custom filter would look something like this:

    import re
    REGEX = re.compile(r"""\\\\(?!['"\\abnfrtvoxNuU])""")
    def backslash_escape(string):
        replacement = r"\\\\\\\\"
        return REGEX.sub(replacement, string)

And after registering it, the cases code like:

    input_string = '{{ case["input"]["encoded"] |backslash_escape}}'

**Comment by yawpitch** [comment]
Thanks @AnAccountForReportingBugs for the inspiration ... that regex isn't really strict enough, as many of those valid escapes are only valid with very specific characters following, but it pushed me to write out the real (and painful) regex required, see #2181 for details.

**Comment by AnAccountForReportingBugs** [comment]
I wanted to make clear, for the record, that was a conscious decision. The point of the change in cpython is to avoid ambiguous code.  For example, is `\[`a mistake because they meant `\\[` or did they do it because they thought they were actually escaping the bracket? The assuming it is the former allows errors to pass silently, and may be the wrong intent of the programmer.

Which gets to my reasoning about the escapes. If the code has something like `hello \u123r!` Is that a bug escape (an r instead of a 4?) or did they mean `\\u123r` so it is literal text? By silently changing things in the background you avoid the `SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 5-9: truncated \uXXXX escape` because you are assuming it wasn't meant to be an escape. I'd rather have the interpreter warn of an error, so it can be fixed, rather than plow over it.

The only thing that really makes me unhappy about my regular expression is that it doesn't really handle arbitrary numbers of backslashes, but that is probably the perfect being the enemy of the good.

**Comment by yawpitch** [comment]
Fair enough. My argument for making the regex tighter here is that we only want to _not_ double escape precisely those sequences in the canonical data that Python considers correctly escaped already. We’re assuming that the test data is intended to be a legal string which will throw no warnings or errors in the generated test code itself ... therefore we assume that the writer of the canonical data either intended to include a legal Unicode literal or they intended to include a (possibly unnecessary, but legal) escaped backslash for the student to deal with. So if they include “\u123r!” we presume they intended to write “\\u123r!” because we toss a coin and err on the side of the upstream committer’s intent not being to break Python’s tests, but rather to break the student’s solution. If I’ve made a mistake in that assumption it will wash out downstream, but I believe it’s correct for now.

**Comment by AnAccountForReportingBugs** [comment]
Yeah, you are probably right on all counts and I agree with the choice made here. I wasn't attacking yours or defending mine, I just wanted to make clear what I was thinking and the decisions made in light of the points you made, in case I missed something or if I or anyone else wants to reuse either expression in the future. But thanks for your response and clarification.

**Comment by yawpitch** [comment]
No worries, I just wanted to have both our thoughts down in case I'm wrong and we need to revisit in the future.
