### ISSUE TITLE
Problems with Tisbury Treasure Hunt

### ISSUE THREAD

**Issue by rcardenes** [exercism/python#2502]
* Instructions ask to return `" not a match."` (including a period) for `create_record` under certain conditions. The tests look for `"not a match"` (no period)
* The instructions look quite ugly in the editor mode. There are two tables that are supposed to go side by side, but they end up one over the other. That combined with the heading ("Azara's List  <> Rui's List") is rather confusing.

**Comment by rcardenes** [comment]
Main issue is the testing, of course. Maybe U should have opened two issues. The UX one is only a problem in editor mode, at any rate

**Comment by BethanyG** [comment]
No worries at all!  It was a really good catch, and an important reminder.  That `tuples` exercise was the very first one written for the track, so there are a lot of things that have gotten changed and re-arranged since.  I am grateful your eagle eye caught the typo -- things like that _seem_ small, but they **really** frustrate users - especially when it is a spec/test difference!

**Comment by BethanyG** [comment]
Fixed in [PR #2503](https://github.com/exercism/python/pull/2503)

**Comment by rcardenes** [comment]
Oh, no eagle eye at all. I'm trying to redo _all_ the exercises (or at least as many as I can) to try and catch this stuff.
