### ISSUE TITLE
Unknown marking detected by pytest: pytest.mark.task

### ISSUE THREAD

**Issue by eirnym** [exercism/python#2536]
This marker seems to be not defined anywhere on resources given to a student (see docs folder). Thus with typical installation using virtual environment with only `pytest` and `pytest-cache` installed as suggested in TEST.md file, a student will get a warning such as below. I suggest to extend documentation or a setup, which student downloads using `exercism` command by including this mark at least as suggested in [official documentation](https://docs.pytest.org/en/stable/example/markers.html#mark-examples)

```python
filename_test.py: PytestUnknownMarkWarning: Unknown pytest.mark.task - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.task(taskno=5)
```

**Comment by BethanyG** [comment]
Hi @eirnym 👋🏽   Thanks for logging this issue!  Yes - agree we should have instructions (_at the very least_) on how to register the marks - or a `pytest.ini` file that can be used so that PyTest won't complain locally.

The marks are not for selecting tests or resources -- they're being used by our track test runner to associate Concept exercise `task numbers` to `tests`, so that the website UI display can show the test code in task order after a test run (_the web UI doesn't display the test file for concept exercises_).  

We use the same test files for the website that are downloaded via the CLI -- so unfortunately, the mark shows up for local runs as well.  If you are curious about the test runner interface, you can take a look at [this specification ](https://exercism.org/docs/building/tooling/test-runners/interface)for track test runners.

The marks aren't being used meaningfully in the CLI context right now. 

We haven't gotten around to updating the "run this locally" documentation yet with register/disable/config info.  😅   Hopefully, we can do that soon, and also include a `pytest.ini` file as part of the general exercise download.

Meanwhile, you can avoid the nag by running pytest locally with the `--disable-pytest-warnings` flag, or adding the following in a `pytest.ini` file in the exercism `python` directory:

```code
[pytest]
markers =
    task: A concept exercise task.
```

**Comment by BethanyG** [comment]
I've logged the `ini` file and documentation tasks as bug #2539.

**Comment by eirnym** [comment]
why this issue is not a bug report?

**Comment by BethanyG** [comment]
Because I was tired, and had also re-logged this as issue #2539, for clarity in what needs changing. 😄     Closing this now in favor of that issue.
