### ISSUE TITLE
Pretty Leaflet & Restaurant Rozalynn locked, but pre-reqs achieved

### ISSUE THREAD

**Issue by Ou42** [exercism/python#2542]
Pretty Leaflet & Restaurant Rozalynn are still locked even though (AFAICT) I have solved their respective prerequisites.

**Comment by BethanyG** [comment]
@Ou42  _Apologies!_  These two exercises should not have been visible on the website.  
`Pretty Leaflet` requires a re-write so that the student isn't forced to create a `class` (_which doesn't have a learning exercise yet_).  See issue #2438.

`Restaurant Rozalynn` has prerequisites that are also not (yet) present in the tree, so should not have been flagged to show on the website.  

I will be pushing a PR shortly that will remove both exercises from public visibility shortly.

**Comment by Ou42** [comment]
Ah-ha! TY.

My goal is to get to the REST-Api exercise and both of the above are listed as requirements.

I'm new to github issues ... Do I "close" this issue being the one that opened it or do you being the maintainer?

**Comment by BethanyG** [comment]
This closed automagically when I linked it to the PR that removed the exercises.  HOWEVER, I also might need to remove the pre-requisites from `REST-API` 😱   _my apologies_ if it does not now unlock.  Please let me know if it does not.  I think you can re-open this issue...or you can open a new one if you are still blocked.  Thank you so much for your patience!  😄

**Comment by Ou42** [comment]
Just confirming, the total number of exercises is now 129, which I believe is smaller than before.
... and instead of 5 available exercises I now have 94 available ( unlocked ).

**Comment by BethanyG** [comment]
We did deprecate a few practice exercises as well...so the practice exercise count should be smaller than what you're used to for the former site.  I also `wip`ed three concept exercises, so there is that as well.  😄    But I think now you should be able to take on REST-API (YAY!).  Have fun coding.  And let us know how it goes.... 🌟
