### ISSUE TITLE
Task 3 of the Meltdown exercise makes no sense

### ISSUE THREAD

**Issue by pranasziaukas** [exercism/python#2585]
Task 3 of the `meltdown-mitigation` exercise makes no sense IMO.

Some output `temperature * neutrons_produced_per_second` is compared to the `threshold` as described by the following 3 cases:
https://github.com/exercism/python/blob/43294ee33627fed530b832d5c38d0155d5021913/exercises/concept/meltdown-mitigation/.docs/instructions.md#L59-L67

All in all, the following intervals (as percentages of the given threshold) are implied:
- `[0; 40)`
- `[90; 110]`
- `[40; 90)` and `(110; +∞)`

`[40; 90)` means `DANGER` and that "the reactor is going into meltdown", which makes no sense as it sits right above the `LOW` territory of `[0; 40)`. It is effectively not possible to continuously transition the reactor from `LOW` to `NORMAL` without going into meltdown...

Can it be that there was a typo and the `LOW` interval is supposed to be `[0; 90)`?

Then the resulting intervals would be:
- `[0; 90)`
- `[90; 110]`
- `(110; +∞)`

It might simplify the exercise slightly but at least then it would make logical sense.

**Comment by pranasziaukas** [comment]
P.S. The tests don't cover the `[40; 90)` case anyway so only the description would need to be changed.

**Comment by BethanyG** [comment]
Normally, I wouldn't say this..but given all the discussion around the first task in this exercise and all the comments on [PR 2568](https://github.com/exercism/python/pull/2568), I am a bit worried we'll create even more issues by making more adjustments to this exercise at this time.  

Could I ask you to coordinate this issue and your [PR 2584](https://github.com/exercism/python/pull/2584) with @kbuc, who has taken on generally reviewing and improving this exercise?  

I think it might be best if you discussed the exercise with him and let him coordinate  and think through changes, since he's put in so much effort already, and will have to make updates to his branch and work.  I love that many people are engaged with this exercise -- but I also don't want all the discussion to end up creating more (unintentional) work or more typos/inconsistencies. 

Thanks for understanding.  😄

**Comment by BethanyG** [comment]
@pranasziaukas  -- if you have time, the "churn" on `Meltdown Mitigation` has slowed, so this issue can be taken up again.  PRs #2568  &  #2584 have been merged.  I am going to take this off `hold`.  Let me know if you'd like to work on it.  Thanks! 🌟
