### ISSUE TITLE
little-sisters-vocab: exemplar uses untaught concepts

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/python#2588]
I noticed that the [exemplar.py](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.meta/exemplar.py) of `little-sisters-vocab` uses indexes and index ranges on a string, but these concepts were never taught to the student. The concept `lists` only appears later on.

This exercise should only appear after the `lists` concept, with an explanation that strings can also be seen as lists. Alternatively, the description of this exercise / concept, should explain the idea of seeing strings as lists and provide examples similar to the ones the student will be asked to do in the exercise.

**Comment by BethanyG** [comment]
Hi @andrerfcsantos  👋🏽   Thanks for logging this issue. 

I think you may be both confused and a bit mistaken.  This exercise does indeed [teach indexing and slicing](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.docs/introduction.md) for `str`, because strings (like `lists` and `tuples`) are a [sequence type](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str).  As such, they support all [common sequence operations](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range).  

There will be an additional follow-on exercise `sequences` which will explore this in more detail, but the concept of indexing and slicing is core to `str`, and we felt it was easiest to introduce that concept here before getting into more complex slicing and slice-assignment manipulations in the `sequences` exercise.

>This exercise should only appear after the lists concept, with an explanation that strings can also be seen as lists. Alternatively, the description of this exercise / concept, should explain the idea of seeing strings as lists and provide examples similar to the ones the student will be asked to do in the exercise.

I strongly disagree.  I  don't think we should be teaching that strings can be seen as `lists`.  That is not at all accurate.  **Strings are immutable** and not a container type.  While they are a combination of unicode code points, they are not a **_collection_** of them.  Python does not have a singular `char` or `rune` type.   `lists` are mutable and **are** a container type.  They can point to arbitrarily typed data, and can be of arbitrary length.  

The two types may share common sequence operations, but the similarity effectively stops there.

That being said, `make_word_groups()` does indeed take as input a `list` and `noun_to_verb()` uses an index on `split()` (_which returns a `list`_) in the `exemplar.py`. 

I would argue that there is a clear example for `split()` with wording about how indexes can apply to `lists` in the `introduction.md` of the exercise, and the `str.join()` example clearly uses  a `list` to demonstrate its use.  There is also reference to common sequence operations.  

The [concept exercise spec](https://github.com/exercism/docs/blob/main/building/tracks/concept-exercises.md#file-docsintroductionmd) doesn't say we can only use one concept -- just that the student should be given everything needed to solve the exercise.

I will think on it a bit.  I don't think making `lists` a prerequisite would be a good idea - we have to start somewhere, and `numbers` and `str` are a solid place to do so.

**Comment by andrerfcsantos** [comment]
> I think you may be both confused and a bit mistaken. This exercise does indeed teach indexing and slicing for str, because strings (like lists and tuples) are a sequence type. As such, they support all common sequence operations.

This is my bad, I completely missed it. I was just looking at the concept `about` and the exercise instructions before entering the editor. Completely forgot to check the instructions in the editor.

Checking those instructions, I think they are really good and do teach about everything that's needed for the exercise, so you can disregard my feedback. Sorry for taking your time with this.

> I will think on it a bit. I don't think making lists a prerequisite would be a good idea - we have to start somewhere, and numbers and str are a solid place to do so.

You made good points and I agree with them. The reason for me opening the issue was the exercise not teaching something that it does teach, so feel free to close the issue.

**Comment by BethanyG** [comment]
> This is my bad, I completely missed it. I was just looking at the concept about and the exercise instructions before entering the editor. Completely forgot to check the instructions in the editor.

This concerns me quite a bit, since it feels all too easy to skip to the code part ...and thereby miss out on vital information!   The only place the information is showing is in the `introduction.md` _after_ you click through to the editor.  🤔   Feels like there **is** a bug of some sort there, or at the very least we should examine what information we put in the concept `introduction.md`.

> Checking those instructions, I think they are really good and do teach about everything that's needed for the exercise

Thank you for that.  😄   I _may_ update these with an add-in from the `lists` exercise.  Feels like it might clarify indexing a bit:

![image](https://user-images.githubusercontent.com/5923094/133694967-9d95cf83-8e7b-44ea-8fc9-a6cc2e44444f.png)
