### ISSUE TITLE
Python track strings_test.py unfinished

### ISSUE THREAD

**Issue by Urkchar** [exercism/python#2609]
When using the local cli, I downloaded the exercise for Little Sister's Vocabulary. This gave me `strings.py` and `strings_test.py`.
The tests were left incomplete. In all other test files that I've used, they've ended with 
```py
if __name__ == "__main__":
    unittest.main()
```
however `strings_test.py` does not have this code. This means that, when running the test file, none of the tests are actually ran. To fix this, add 
```py
if __name__ == "__main__":
    unittest.main()
```
to the end of `strings_test.py`
I think this could be a good time for a pull request but it seems like I can't do that. Nor do I really know how.

**Comment by BethanyG** [comment]
@Urkchar  -- That code does indeed allow the test file to be run stand-alone (_invoking `unittest` as the test runner_), and we will start omitting it from new exercises and removing it from older ones going forward.  

I've allowed it to hang around because I didn't think it was harming anything -- but it appears to be causing confusion about how our tests should be run and is causing an uptick in PRs to add the code to exercises that don't need it.

Tests for this track need to be run using [PyTest](https://docs.pytest.org/en/6.2.x/getting-started.html#install-pytest) going forward.  Running the test file as a module from the command line or your IDE will cease to work for many exercises, because `unittest` cannot run tests that use `PyTest` features.

We now rely quite heavily on some  PyTest features in our online test runner, and will be introducing more dependency as we roll out automated analysis and representation.  Longer-term, we have plans to make those features available as a PyTest plugin for users who are working on their own machines via the CLI, and writing tests that use `PyTest`-style  assterts and fixtures.

That means that users really should be installing, getting familiar with, and using `PyTest` now, and not relying on "just running" the test file (_even thought that may continue to work for some exercises_).  

Running tests that have PyTest features using `unittest` will fail or have unexpected results,  but running `unittest` tests with PyTest will succeed.
