### ISSUE TITLE
[Currency Exchange] Confusing Wording and Directions

### ISSUE THREAD

**Issue by BrooksAz** [exercism/python#2621]
The actual coding work is extremely easy, it's just basic arithmetic. The problem is understanding what you are supposed to be calculating. Everything is easy until task 5, when you-know-what hits the fan, at least for me. In the beginning, budget was a total, and we were just taking a portion out of it to be used, with exchanging value and such. Now it appears we are spending it all in one place? Then comes in denomination. Is this the denomination of the original bill or the new foreign bill? And are we getting the number of original bills or new foreign bills. I'm sorry for being disorganized but I am stumped by this exercise even though it is seemingly a simple concept.

**Comment by epyklion** [comment]
I agree

**Comment by BethanyG** [comment]
Hi @BrooksAz 👋🏽  

Thanks for logging this.  @epyklion - thanks for commenting. 🌟 🌈 

Please take a look at the discussion in [Issue 2591](https://github.com/exercism/python/issues/2591) (now closed as fixed by [PR 2601](https://github.com/exercism/python/pull/2601 )).  I think some of the comments there might help clarify things a bit.

We'd also love if you have any suggestions or thoughts on how to improve this exercise, since it seem to be giving people lots of issues -- despite us having re-written it a couple of times.

Comments (or a PR) of what you think might be a better fit with the story and the tasks (numbers) would be warmly welcomed.  😄

**Comment by Bixxith** [comment]
Would it be a bad thing to just say "to calculate this you need to take the quotient of x and y and then find the product of the resulting number and z"?  It would shift the focus of the problem from trying to comprehend currency exchange to implementing mathematical equations and working with numbers.

**Comment by BrooksAz** [comment]
> Would it be a bad thing to just say "to calculate this you need to take the quotient of x and y and then find the product of the resulting number and z"?  It would shift the focus of the problem from trying to comprehend currency exchange to implementing mathematical equations and working with numbers. 

I think it would be better to have some aspect of identifying the problem, but add in hints for every step that point you in the right direction.

**Comment by BrooksAz** [comment]
I have created a pull request which I think clears up a lot of the vagueness that currently exists in the exercise.

**Comment by BethanyG** [comment]
@BrooksAz  -- could you please link that PR to this issue?  Many thanks. 🌟  I will try to review & comment on it later today my time (I am in PST).

**Comment by BrooksAz** [comment]
Right here - [https://github.com/exercism/python/pull/2626](url)

**Comment by BrooksAz** [comment]
#2626 Right here

**Comment by BethanyG** [comment]
Please see also [issue #2804](https://github.com/exercism/python/issues/2804) (_closed in favor of tracking feedback here_), which has additional feedback and comments for improvement.

**Comment by BethanyG** [comment]
Since we're being slow in re-writing this exercise and decided to merge #2804, I am going to close this issue as resolved -- until we re-design/re-write the exercise.
