### ISSUE TITLE
[Supported Language Versions] Possible Move to Python >= 3.10 for Tooling and Exercises

### ISSUE THREAD

**Issue by AdamJel** [exercism/python#2656]
Hi, 

using `match case` syntax from python 3.10 raises errors and causes solution to fail.

Please, bump python version.

**Comment by MatthijsBlom** [comment]
I understand last october was not the time to upgrade to 3.10. However, perhaps now is the time?

Can I help?

By the way: I feel like this issue should be reopened and the label _wontfix_ removed, as at present it gives the impression this wil _never_ be fixed &ndash; which I do not think is the intention.

**Comment by BethanyG** [comment]
@MatthijsBlom   - I wouldn't expect a discussion on 3.10 before June, or possibly later.  There is just too much other work for the track and the tooling.  It's far more important that we get content, tests, and analysis in place for the track than it is we support the "latest" version of the language.  And given that the Python 3.10.2 was expedited because 3.10 had some unfortunate bugs...well...things need to settle a bit.

If you would like to help, the best way to do so at this time is to create or improve track exercises, tests, and concepts -- or mentor.  

As for the `won't fix` -- while it is fair to bring up the issue, it is not fair to imply that we'll be starting discussions or work on it on it any time soon.  So in re-opening this, I will be tagging it `hold` and `discussion`.

**Comment by BethanyG** [comment]
@MatthijsBlom @AdamJel  -- It's now July, and Python 3.11 is in `beta`.  Time flies!

I think we might be ready to take the plunge and start upgrading our tooling to 3.10.  This (mostly) means testing the tooling, CI, and exercises to make sure everything works with 3.10 and doesn't explode.  The CI for the Python track in particular might need a good looking over.  Would either of you still be interested in helping out with this?  Let me know.  😄

**Comment by BethanyG** [comment]
Once I hear back, we can put together a checklist of what needs to happen and log a tracking issue either here or in the tooling repos.

**Comment by MatthijsBlom** [comment]
Sure, I'm in.

**Comment by BethanyG** [comment]
@MatthijsBlom  - we went ahead and bit the bullet, but would LOVE more testing/attention on Python `3.10.6` - specific features, so if you'd like to go to town on your favorite practice or concept exercise using `3.10.6` features and report any weird things you see, that would be much appreciated!  😄

**Comment by MatthijsBlom** [comment]
The solution I suspect brought this issue to my attention [is now accepted](https://exercism.org/tracks/python/exercises/tournament/solutions/MatthijsBlom). I remember trying to use [PEP 618](https://peps.python.org/pep-0618/)'s optional length-checking in `zip`, and even wishing for its extension to `map`, but I cannot find the relevant exercises now. Not sure what else there is to test.
