### ISSUE TITLE
Meltdown Mitigation has wrong Test cases?

### ISSUE THREAD

**Issue by JAdelhelm** [exercism/python#2775]
![image](https://user-images.githubusercontent.com/83546217/141785265-c7ecf5c9-52de-4662-83a6-62000d392274.png)

The output should be DANGER and not NORMAL or am I wrong?

Example Test Case :
MeltdownMitigation > fail safe [variation #5] (expected='NORMAL', neutrons per second=901, temp=10, threshold=10000)

neutrons per second = 901
temp = 10

tempNeutrons = 901*10 = 9010
ratio = 9010/10000 = 90.1 % --> Out of zones = "DANGER"

**Comment by J08K** [comment]
Hi there,
I think you might be missing something about the exercise. For the reactor to be `normal` it is between 10% difference of a 100% of the threshold. So it would be between 90% and 110%. So the tests are correct, since you came out at 90.1%. 
![image](https://user-images.githubusercontent.com/48634934/141794482-dbafd15d-2f53-488a-9e8b-a16ed2893c21.png)
Anyway, have a nice day, and if you are having problems with this exercise please contact a mentor.
