### ISSUE TITLE
[Concept Exercises] Strings Concept needs Conditionals and Booleans as pre-requisites

### ISSUE THREAD

**Issue by martinfreedman** [exercism/python#2795]
This applies to the ` Little Sister's Vocabulary` the first unlocked strings concept exercise. It requires the Conditionals concept in order to complete some of the tests.

**Comment by BethanyG** [comment]
Thanks for catching this, @martinfreedman!  We'll get a fix out as soon as we can.

**Comment by BethanyG** [comment]
Just wanted to update this, since this has been sitting for 9 days 😱 .

Since this is a change to the track `config.json`, we decided to get some other things cleaned up first.  Once we have some of our linting, bug fixing, and new exercise changes through, we'll PR this.  ETA most likely in the next week.

Thanks for your patience.  😄
