### ISSUE TITLE
[Wordy]:  Conflicting Expected Error Messages in Exercise Tests

### ISSUE THREAD

**Issue by googlymog** [exercism/python#2799]
I'm having trouble with the tests on Wordy.  Below are two test which test two operators and numbers in a row respectively.  Each expect a ValueError with the text 'syntax error'.

```python
def test_reject_two_operations_in_a_row(self):
    with self.assertRaises(ValueError) as err:
        answer("What is 1 plus plus 2?")
    self.assertEqual(type(err.exception), ValueError)
    self.assertEqual(err.exception.args[0], "syntax error")
def test_reject_two_numbers_in_a_row(self):
    with self.assertRaises(ValueError) as err:
        answer("What is 1 plus 2 1?")
    self.assertEqual(type(err.exception), ValueError)
    self.assertEqual(err.exception.args[0], "syntax error")
```

And these are the track specific tests which test two numbers and operators in a row respectively.  Each expect a ValueError with the text 'unknown operation'.

```python
def test_missing_operation(self):
    with self.assertRaises(ValueError) as err:
        answer("What is 2 2 minus 3?")
    self.assertEqual(type(err.exception), ValueError)
    self.assertEqual(err.exception.args[0], "unknown operation")
def test_missing_number(self):
    with self.assertRaises(ValueError) as err:
        answer("What is 7 plus multiplied by -2?")
    self.assertEqual(type(err.exception), ValueError)
    self.assertEqual(err.exception.args[0], "unknown operation")
```

I believe both of these sets of tests should return the same error, probably 'syntax error'.  Or, the text of the error shouldn't matter to pass the test.  Happy to hear others' thoughts.  Thanks for reading.

**Comment by BethanyG** [comment]
Hi @googlymog 👋🏽 

Thanks for filing this issue.  Apologies that it's taken a while to get back to you.

> _I believe both of these sets of tests should return the same error, probably 'syntax error'. Or, the text of the error shouldn't matter to pass the test._

I agree that an argument could be made for the error messages you cited matching, and that `syntax error` makes the most sense, given the tests and the context.  **_However_** the following cases (_which come straight from [problem-specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/wordy/canonical-data.json), are rightfully "unknown operations", and should not match the others:

```python
   def test_unknown_operation(self):
        with self.assertRaises(ValueError) as err:
            answer("What is 52 cubed?")
        self.assertEqual(type(err.exception), ValueError)
        self.assertEqual(err.exception.args[0], "unknown operation")

    def test_non_math_question(self):
        with self.assertRaises(ValueError) as err:
            answer("Who is the President of the United States?")
        self.assertEqual(type(err.exception), ValueError)
        self.assertEqual(err.exception.args[0], "unknown operation")
```

I don't think we should go back to not having error message text matter -- learning to return specific (and meaningful) error messages is very important -- we just didn't quite get the "meaningful" right for some of the cases in this exercise.

PR #2807 changes the Python-specific test cases to check for `syntax error`.  If you think that `unknown operation` is not an error message that should be returned, I would suggest filing an issue in [problem-specifications](https://github.com/exercism/problem-specifications/), so that it can be discussed cross-track.

**Comment by googlymog** [comment]
Hi @BethanyG 👋,
Thank you for taking the time to respond and explaining your reasoning.  I agree 100% with what you decided, the python track specific tests should cause a syntax error.  Also, thank you for submitting a PR and fixing the issue.
