### ISSUE TITLE
[Cater-Waiter] Test Data Files Not Copied to Analyzer - Website analysis fails with ImportError

### ISSUE THREAD

**Issue by goatthinking** [exercism/python#2815]
Website link: https://exercism.org/tracks/python/exercises/cater-waiter
Git link: https://github.com/exercism/python/tree/main/exercises/concept/cater-waiter

Tests fail if just submitting `sets.py` 
```none
AN ERROR OCCURRED
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

However the tests pass locally.
```none
[cater-waiter]$ pytest .

<REMOVED FOR SPACE>

sets_test.py:99
  ~/Exercism/python/cater-waiter/sets_test.py:99: PytestUnknownMarkWarning: Unknown pytest.mark.task - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.task(taskno=7)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================= 7 passed, 7 warnings in 0.04s ==========================================================
```

Data from `sets_categories_data.py` & `sets_test_data.py` is needed as well. I found this out due to 
* https://exercism.org/tracks/python/exercises/cater-waiter/solutions/ckush
* I tried with just submitting `sets.py` `sets_categories_data.py` but that is not enough.

However `sets_test_data.py` is too large to submit and shoots an error on max allowed file size when trying to submit.

```none
[cater-waiter]$ exercism submit sets.py sets_categories_data.py sets_test_data.py
Error:

      The submitted file '~/Exercism/python/cater-waiter/sets_test_data.py' is larger than the max allowed file size of 65535 bytes.
      Please reduce the size of the file and try again.
```

Currently there is no way to pass this exercise.

**Comment by BethanyG** [comment]
Hi @goatthinking 👋🏽 

Thank you for filing this issue.  I think there are actually two problems here, and your solution got tangled up in them.

The first error you are seeing is actually tied to some maintenance work on old solutions that has been running in the background.  We've been running all community solutions (_seven years worth!!_) on all tracks against the most recent version of the tests, and that's been causing some delays and timeouts across the system.  Things got slow and then re-set sometime around noon GMT today. It's likely that if you re-tried your solution on the site now (_Noon PST_), it would process without error.

There should be no need to re-upload the `test data` files for this exercise, since we make a copy server-side when we run the tests.

However, you would probably see the issue I've just hit in re-testing this.  While the **_tests_** do indeed pass for a solution uploaded _without_ the test data, **_analysis_** fails with missing files:

![image](https://user-images.githubusercontent.com/5923094/145468122-6a4b6ea5-f6d6-421f-95cc-a7ba2a0664d7.png)


I'm currently investigating the analyzer issue, and will keep you posted.  

Please let me know if you are still having timeout issues for tests on the site, and if you have any additional questions or issues.

**Comment by BethanyG** [comment]
As it turns out, the test data files were not being copied over to the space where the analyzer could use them.  This should be addressed in https://github.com/exercism/website/pull/2257, which is not yet merged.  Will hold this issue open until that issue is merged.

**Comment by BethanyG** [comment]
Closing, since https://github.com/exercism/website/pull/2257 has now been merged.
