### ISSUE TITLE
Seive tests can check for div/mod

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2828]
It occurs to me that the tests of the Sieve problem can check to make sure the user isn't using a disallowed function.

https://stackoverflow.com/questions/427453/how-can-i-get-the-source-code-of-a-python-function

`/`, `%`, and the entries from `operator` too

Whatever you come up with can be circumvented of course, but that's true of any test (someone can just hard-code the results based on the input). I think it'd be valuable to do; some users may use them accidentally.

**Comment by BethanyG** [comment]
Hi @mohmad-null,

Thanks for logging this.  The directions in this case specifically say that it is up to the student to check if they are using "disallowed" operators -- the tests don't check for them.  

That being said, `Seive` tests on the Python track are auto-generated from [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/sieve), so if you want to suggest additional scenarios, you will want to start there with an issue or PR, so that maintainers across the tracks can discuss it and weigh in.

With that in mind, I am going to close this issue for now.  Should we decide this is a Python-specific issue, we can discuss making an addendum or extra Python-specific tests.
