### ISSUE TITLE
Two-Fer exercise recommends against input validation.

### ISSUE THREAD

**Issue by piccoloser** [exercism/python#2830]
My solution to the Two-Fer exercise included a test for `isinstance(name, str)`, and the analyzer states that conditionals are used unnecessarily. This could be a completely preferential thing and I'm just over-engineering, but I feel like input validation shouldn't be considered "unnecessary."

If I'm wrong about this, at least I'll have learned something haha

**Comment by BethanyG** [comment]
Hi @piccoloser!

Thanks for logging this!  😄   Without seeing your solution, I can't comment in detail.  But having worked on the Analyzer for this exercise, and had MANY discussions about it, I can say that there is an "exemplar" solution that avoids the need for any sort of input validation -- hence the feedback.

The spec (and tests) ask that you return a `str` composed of the input and some other words.  Given that you can coerce most types to `str` in Python means you need not check that the input given **is** a `str` -- only that you can _make_  it _into_ one.  It would be very very different if you needed to process the `str` and do further analysis -- in that case you'd probably want a checking/cleaning/conversion step.  You might even want to wrap the whole thing in a `try-except`.

But there is another catch to this particular problem.  And it caused major issues back when this was the first problem listed on the track.  The canonical solution uses a [default argument](https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions) that is a `str`, and employs an [f-string](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) for the return.

Since an `f-string` will _always_ convert any and all types inside to a `str`, input is taken care of.  A default argument that is `name='you'` takes care of any cases that might be empty.  But if you don't hit on that particular combination (_many students use a default argument of `name=None` and `+` for string concatenation_), you set yourself up for all sorts of checking and error handling -- which is a rude trick to play on someone when they are expecting an easy problem to solve!

 As it turns out, flavors of function arguments in Python are far from a beginner topic.  And with Python 3.10, the variations have become quite crazy.  IMHO, they've probably gone too far.  We're in the process of thinking about just exactly how many concept exercise we need to make to help students through the mess.  😅   

But I digress -- the feedback for checking `isinstance` is in there because for the canonical solution, its unnecessary.  That doesn't mean that in a different context it wouldn't be needed, or that checking for type is bad -- just that _here_ its not ideal.

**Comment by piccoloser** [comment]
@BethanyG, thanks for your reply! Your explanation makes a lot of sense actually, I appreciate it.

This is the solution I implemented:
```python
'''Return a string stating "One for [name or 'you'], one for me."'''


def two_fer(name: str = "you") -> str:
    '''
    Plug a string (name) into the phrase, "One for (name), one for me."
    If nothing is provided, name defaults to 'you'.

        Parameters:
            name <str>: name that gets plugged into the output
    '''

    if not isinstance(name, str):
        raise TypeError(f"two_fer() expects a str, but got {type(name)!r}")

    return f"One for {name}, one for me."
```

It makes sense that type-checking would be unnecessary now that you mention `f-string` behavior (to be honest, I'd forgotten about that lol). Thanks again for clarifying!

**Comment by BethanyG** [comment]
@piccoloser

_You are most welcome!_.  And all that being said -- I can clearly see why you'd want to be suspicious if you were taking in "random" user input.  (_users are creative and terrible engines of chaos!_).  Certainly something to think through if this was part of a larger program or was a method designed to interact with an entry screen.  Also something to **_really_** think through if the string you are building and passing back is intended for a downstream process to act on.  That recent log4J bug is no joke -- and neither are un-sanitized DB inputs.  😉   

When I used to mentor this problem a lot, I would refer to this post on [Real Python](https://realpython.com/python-string-formatting/),  I love how he breaks down the reasoning behind the different string formatting options and goes over benefits and pitfalls.

Thanks again for logging this.  I will keep it open for a bit and then close -- unless you have other questions or issues?

**Comment by piccoloser** [comment]
I think that should do it; I appreciate the info and quick response!
