### ISSUE TITLE
[Currency Exchange] What to do in Task 6( non_exchangable_value)?

### ISSUE THREAD

**Issue by generalpy101** [exercism/python#2835]
All my tasks are done but I don't know what to do in task 6. It says to calculate non exhangable values but I don't know how to calculate that. Can someone please provide me formula for that.
My current code : 
```
def exchange_money(budget, exchange_rate):

    return budget/exchange_rate


def get_change(budget, exchanging_value):
   
    return budget - exchanging_value


def get_value_of_bills(denomination, number_of_bills):
    
    return denomination * number_of_bills

def get_number_of_bills(budget, denomination):
   
    return int(budget // denomination)


def exchangeable_value(budget, exchange_rate, spread, denomination):
   
    _exchange_rate = exchange_rate + exchange_rate * (spread / 100)
    res = (exchange_money(budget,_exchange_rate) // denomination) * denomination
    return int(res)


def non_exchangeable_value(budget, exchange_rate, spread, denomination):
    temp = ((budget*denomination) - exchangeable_value(budget,exchange_rate,spread,denomination))//denomination
    print(budget*denomination , exchangeable_value(budget,exchange_rate,spread,denomination))
    return int(temp)

```

Please ignore non_exchangable_value() function, I know it is wrong.

**Comment by BethanyG** [comment]
Hi @generalpy101 👋🏽 

I think you're _almost_ there -- but got a little confused by the wording of the task (_our apologies there!_).  In `task 5`, we ask you to calculate what **_can be_** exchanged - which you have done. 

 In `task 6`, we're asking what the "waste" , "leftover", or "remainder" there might be from `task 5`.  So if you take your formula from `task 5`:

```python

def exchangeable_value(budget, exchange_rate, spread, denomination):
   
    _exchange_rate = exchange_rate + exchange_rate * (spread / 100)
    res = (exchange_money(budget,_exchange_rate) // denomination) * denomination
    return int(res)

```

And make a small change to use the _**modulo**_ (_see the table on [this page](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex) in the Python docs_) operator:

```python
def exchangeable_value(budget, exchange_rate, spread, denomination):
   
    _exchange_rate = exchange_rate + exchange_rate * (spread / 100)
    res = (exchange_money(budget,_exchange_rate) % denomination)
    return int(res)
```

It should give you the remainder (leftover) instead of the exchangeable value.

**Comment by BethanyG** [comment]
@generalpy101  -- Please let us know if that helps/answers your question.  I will leave this open for another day and close it after unless you have additional questions or issues.  Thanks!

**Comment by generalpy101** [comment]
Thanks fo your answer @BethanyG . I understood the answer and have no further questions. The fact that modulo can be used to find remainder slipped my mind. Thanks for your answer!!!
