### ISSUE TITLE
Error Messages Should Include Line Numbers

### ISSUE THREAD

**Issue by astrieanna** [exercism/python#2855]
One of the most consistently frustrating experiences when doing Python Exercism exercises is the feedback for code that doesn't work -- that throws an error do to a typo or similar. In a normal coding environment, I would always expected to get a line number with my error message. But in Exercism, I do not get a line number.

This is the place that I see errors without line numbers:

<img width="536" alt="Screen Shot 2022-01-12 at 9 50 36 PM" src="https://user-images.githubusercontent.com/1205394/149273300-292132e2-2c3f-470f-9258-ae0716e8a3d0.png">

The experience of hunting through code to find the source of the issue is very frustrating.

**Comment by BethanyG** [comment]
Hi @astrieanna 👋🏽 

Thank you for filing this issue.  It is indeed frustrating to have to rummage through your code for an error and not have a line number as a starting point.  Unfortunately, there is not a whole lot we can do about that either in our test runner nor UI at the moment.

Our [Python Test Runner](https://github.com/exercism/python-test-runner) is a [PyTest](https://docs.pytest.org/en/6.2.x/contents.html) plug-in, and uses the same mechanics PyTest does for the reporting of runtime errors:  any runtime error is collected  from the Python runtime and incorporated as part of the test report. 

For the site, we run all student code against tests in isolated [Docker](https://www.docker.com/) containers, and capture resulting errors as they occur and output them to a JSON file for later parsing and display on the website.

All of this is a long-winded way of saying that we don't always have line numbers because we aren't always  **_given_** line numbers by either the Python runtime nor PyTest.

As an example, I wrote code for Two-Fer that tossed the same `TypeError`, and ran PyTest from the command line.  Here's an example of a failed test case:

![image](https://user-images.githubusercontent.com/5923094/149429803-2f3eac29-3eac-47a7-ab18-b193e1ed37e7.png)

Note that while the detailed terminal report (_I set Pytest to verbose for this example_) does show the offending line of code, nowhere are there line numbers for it, and the "final" test summary only includes the error text.

Our test runner currently collects the test code and the final error message.  We don't capture the part where the code and inputs are printed out.  We may consider doing that in the future - but for now we're only doing test code and errors/failures, as doing more code capture requires some significant refactoring.

Suggest that if you can, try using either PyTest locally on your machine with your IDE of choice, or using something like VS code in the cloud with PyTest for more precise/verbose error and test reporting.

**Comment by BethanyG** [comment]
Hi @astrieanna 👋🏽 

Please let me know if you have additional questions or issues.  I am going to close this issue for now -- but please feel free to re-open it (or open other issues), should you need to.  😄

**Comment by astrieanna** [comment]
Thanks! Yes, that makes sense -- that it's not easy to get the right error output for this case.
