### ISSUE TITLE
[Numbers] Update concept and exercise to include definitions of precision, floating-point, conversion

### ISSUE THREAD

**Issue by DjangoFett** [exercism/python#2861]
In the numbers concept introduction, it uses `precision` to describe the differences between ints and floats. It does link to arbitrary precision for ints but would be nice to add a small definition of `precision` before defining ints and floats. This would serve as a good reminder for those that may not have had a strong education in math.

`Narrow` could be more clearly defined too. I found I understood what it meant intrinsically because I understood the difference in the two data types prior to reading the concept. I did a quick search to see what would be returned if someone tried to look up a definition of a narrow number and did not see anything that would be helpful to a student on the track.

<img width="727" alt="Screen Shot 2022-01-20 at 8 01 23 AM" src="https://user-images.githubusercontent.com/2284834/150335759-630e9b6a-4a6a-40f8-91b2-6eb3fe8fa46a.png">
 
I wonder if defining narrow or re-writing the arithmetic section in terms of precision may be clearer?

**Comment by BethanyG** [comment]
Hi @DjangoFett 👋🏽 

Thanks for logging this!  Yes -- I fully agree that we've done a lot of "hand waving" when it comes to precision, numeric types, floating point math, and how Python "converts" numeric types.

The "narrower" usage is cribbed [directly from the Python docs](https://docs.python.org/3.9/library/stdtypes.html#numeric-types-int-float-complex), but doesn't really track well unless you already have a mental map of "wide" (_more decimal places_).  So that section is certainly in need of a preamble.

And while [0.30000000000000004.com](https://0.30000000000000004.com/) does an excellent job of explaining "floating point" and by inference "precision", it's likely that students aren't digging that far into the links and docs to ferret out a definition.

I found the following at [academind](https://academind.com/tutorials/floating-point-precision-and-arithmetic#how-are-computers-dealing-with-that) while digging around for some more links:

> _You might've heard terms like single precision or double precision when defining variables in certain programming languages. That's what they mean - how many numbers (after the decimal point) are stored exactly before rounding occurs_.

[Wolfram](https://mathworld.wolfram.com/Precision.html) is not bad, as it avoids a direct descent into binary:

> _The number of digits used to perform a given computation. The concepts of accuracy and precision are both closely related and often confused. While the accuracy of a number x is given by the number of significant decimal (or other) digits to the right of the decimal point in x, the precision of x is the total number of significant decimal (or other) digits._


I'd be delighted if you wanted to take on re-working some things.  In addition to the `introduction.md` (_which focuses on the knowledge needed to complete the exercise_), there is also:

-   The [**concept**](https://github.com/exercism/python/tree/main/concepts/numbers)  `introduction.md` (summary/less detailed) and the `about.md` (more detailed, "deep" links) 
-   The [exercise](https://github.com/exercism/python/tree/main/exercises/concept/currency-exchange/.docs) `hints.md` file (_for specific help on a task-by-task basis_)
-    The **concept** `links.json` file (_for supplementary learning and application links_)

All of which are intended to work together to help students get their heads wrapped around the topic.  But for numbers, I think we probably need to pull some things forward and push other things "back" -- at least for the exercise introduction.

I look forward to seeing what you come up with!  😄
