### ISSUE TITLE
[Kindergarten Garden] — Test suite contradicts problem instructions

### ISSUE THREAD

**Issue by jaywritescode** [exercism/python#2871]
In the "Kindergarten Garden" problem, the instructions specifically say:

> Given a diagram, determine which plants each child in the kindergarten class is responsible for....

> There are 12 children in the class: Alice, Bob, Charlie, David, Eve, Fred, Ginny, Harriet, Ileana, Joseph, Kincaid, and Larry.

The first seventeen of nineteen tests in the problem's test suite conform to the given instructions; however, the final two unit tests introduce students Samantha, Patricia, Roger, and Xander. These students, according to a reasonable interpretation of the instructions, are _not_ in the class. We are told that the class has twelve children and then given the names of those twelve children. 

Related to #2856, this contradiction could be resolved by removing the childrens' names from the instructions and explicitly passing them into the driver function, or by removing the last two tests in the test suite.

**Comment by BethanyG** [comment]
Hi @jaywritescode 👋🏽 

Thanks for filing this issue!  I agree that the instructions for this exercise might be easily mis-interpreted or mis-read without careful reading of the test file and a bit of trial-and-error.

As outlined in my reply to issue #2856  - the instructions for this `practice` exercise (_actually all current practice exercises_) are cross-track and are maintained in a repo called [problem-specifications](https://github.com/exercism/problem-specifications).  General changes to them are proposed and discussed there between different track maintainers. Only track-specific/language specific appends are PR'd to this repo.

The reason I proposed an `instructions.append` for #2856 was that the poster was talking about `class` interfaces and other OOP details that are (somewhat) specific to Python.  For example, [this same problem in Haskell](https://github.com/exercism/haskell/tree/main/exercises/practice/kindergarten-garden) doesn't have `classes`, because the Haskell programming language doesn't implement them.

However, the issue that **you** are describing gets at the way the core description and tests for this exercise are created.  So your proposed changes should be brought up in [problem-specifications](https://github.com/exercism/problem-specifications), so everyone can talk them through and see if it does indeed make sense to change the wording of the problem, or eliminate or change some of the tests described.

Given that, I am going to close this issue -- but encourage you to take the text of what you've posted here and open an issue for discussion in the `problem-specifications` repo.

**Comment by jaywritescode** [comment]
Thanks for redirecting me to the right place. Much appreciated!
