### ISSUE TITLE
[word-count] instruction suggestion

### ISSUE THREAD

**Issue by zepam** [exercism/python#2877]
I wrote a not very elegant solution to this one, then once I looked at some other solutions I realized that using regex would make things a lot easier. Once I made that switch, it was a much better solution. I wonder if the instructions should drop a hit that regex may be a good way to solve it. I also found [this post](https://github.com/exercism/python/issues/2856#issuecomment-1012673345) that discusses how the Exercises are deliberately designed to cause us to think through the problem more, so maybe the hint is being left out on purpose?

**Comment by BethanyG** [comment]
Hi @zepam   --  Thanks for filing this issue!

Indeed, the [mentor notes](https://github.com/exercism/website-copy/blob/main/tracks/python/exercises/word-count/mentoring.md) for this exercise point to RegEx as a possible solution.  But they also cover the use of `str` methods and additional strategies like using `collections.Counter` to take care of tabulation. 

I am not opposed to putting together a `hints`  file for this exercise that nudges students in the direction of a RegEx, and maybe gives them some links to investigate what the `re` module (as well as `collections` and `str`) can do for them.  Hints for `practice` exercises under V3 are a bit new-ish, so I am not sure how they will display on the site yet, but you can look over the spec [here](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-docshintsmd).  I have on my list to test `hints` out for `practice` exercises  -- so I'd be delighted to collaborate on a PR with you, if you are up for it.  🌟 

I think - for the reasons you linked to - that I would stop short of doing an `instructions.apped` or other commenting in the stub file, since it's quite possible to get a working solution _without_ regex.  Maybe that solution won't be the "most efficient" or "elegant" feeling solution -- (_or maybe it will be!_).  We just don't want to give students the impression that there is only one "right way" to approach the problem, since that closes off their exploration and learning.
____

Instruction detail, stub comments, and hinting have been coming up a lot lately in discussion both here in Git Hub (_as you've seen_), and in our Slack channel.  It's a complicated topic.  😄 

On one hand, we don't want to chase away students with overly-frustrating or obscure or impossibly hard programming problems.  That's not productive.  On the other -- we **do** want to provide both a good problem-solving challenge and an opportunity to engage with mentors and others around approaches and strategies.  Drilling on syntax or data structures only gets you so far.  Hence the divide between `concept` exercises and `practice` exercises.

We've even thought that maybe we need a third "style" of exercise that bridges all the detail of the `concept` exercise and the vagueness of the `practice` exercises.  Would love your thoughts on if that might be needed, and what that might look like.  💛 💙 


Soooo.  `TL;DR`:  Would love to collaborate or review a `hints.md` PR for this exercise, if you're up for it.  😄

**Comment by zepam** [comment]
I think the variety of working solutions is what makes this exercise an interesting one. I'm trying to think of a way to structure a `hints.md` that would acknowledge that while also giving people hints on the different ways to solve it.

Once I figured out that I could use regex, the solution came together quickly. But for beginning programmers, being introduced to Regular Expressions and Counters may feel overwhelming and discouraging that they suddenly have huge things they feel like they "have" to learn for the solution.

Maybe something like this:
If you're a beginner, check out strip() and replace(). Also remember the work you did earlier on dictionaries (with a link to previous problems).
If you're feeling adventurous, check out regex and counters

**Comment by IsaacG** [comment]
While there are certainly elegant ways to [solve this using regex](https://exercism.org/tracks/python/exercises/word-count/solutions/zepam), there are also elegant solutions which [do not use regex](https://exercism.org/tracks/python/exercises/word-count/solutions/IsaacG).

This exercise can certainly be used as a place to practice regex. However, unless the exercise is specifically intended as a regex exercise, I'd be cautious of pushing regex as the "better" solution. While regexes certainly have their place, just because they *can* be used doesn't mean they *should* be used. Xkcd immortalizes this concept in [this comic](https://xkcd.com/1171/) as well as several other regex themed comics.

**Comment by zepam** [comment]
Agreed. Especially for those who aren't familiar with regex, it may feel like more of a mass of confusion rather than a helpful hint. Instead of tagging solutions as "beginner" or "advanced", they could be tagged as... something that I can't think of right now. Essentially a way of saying there are several different ways to solve this and they are all good learning experiences. If you need a hint, here's one. If you've already solved it, try this other way.

**Comment by BethanyG** [comment]
> _Instead of tagging solutions as "beginner" or "advanced", they could be tagged as... something that I can't think of right now._

`THIS`  💜 

and I fully agree:

> _unless the exercise is specifically intended as a regex exercise, I'd be cautious of pushing regex as the "better" solution. While regexes certainly have their place, just because they can be used doesn't mean they should be used._

And to your point above, @zepam  -- I might even remove terms like "beginner" from the hints text.  Because maybe it's less "beginner" vs "advanced", and more choosing to use `str` tools or `dict` tools over importing/using modules like `re` or `collections`.  All are good learning experiences, and the `hints` are about letting someone know what the "paths" or "options" are.

**Comment by zepam** [comment]
Are there examples of other `hints.md` files that provide suggestions for additional options? 
If you think this would be a helpful file, I will browse through the other solutions to come up with some ideas

**Comment by BethanyG** [comment]
@zepam -- I am so sorry!  😱   My intention was not to have you close this -- It just fell through the cracks.  Are you still interested (provided I can find examples)?
