### ISSUE TITLE
[String Methods] Correct typo in config

### ISSUE THREAD

**Issue by Timo4B** [exercism/python#2904]
"," after "translating" should be deleted I think
concepts/string-methods/.meta/config.json

**Comment by BethanyG** [comment]
**Per note in PR:** I disagree with this.  The comma is there because of the `or` -- there is a list of three followed by `or otherwise`, and therefore the comma is warranted  See [Oxford Comma](https://en.wikipedia.org/wiki/Serial_comma#:~:text=In%20English%2Dlanguage%20punctuation%2C%20a,of%20three%20or%20more%20terms.)
