### ISSUE TITLE
[Robot Name] Is this test correct?

### ISSUE THREAD

**Issue by astrieanna** [exercism/python#2913]
In the text of the problem, the robot name generator is supposed to:

> Every once in a while we need to reset a robot to its factory settings, which means that its name gets wiped. The next time you ask, that robot will respond with a new random name.
>
>The names must be random: they should not follow a predictable sequence. Using random names means a risk of collisions. Your solution must ensure that every existing robot has a unique name.

When I read that, I assume that you should be using function from random to generate a name.

[One of the tests](https://github.com/exercism/python/blob/main/exercises/practice/robot-name/robot_name_test.py#L29-L47) generates a name, resets the random seed, resets the robot, and then asserts that the new name is **not** the same as the old name.

This seems like it would mean you can't just generate a random name on reset, since the random number generator reset to the same seed would generate the same name.

I would have expected this test to check literally the opposite -- checking that they *are* equal because the names are generated via RNG (rather than sequentially).

Am I missing something or is the test backwards?

**Comment by IsaacG** [comment]
> The names must be random: they should not follow a predictable sequence. Using random names means a risk of collisions. Your solution must ensure that every existing robot has a unique name.

The names should be random. The names must be unique. Those are independent requirements.

When you randomly generate values, there is a risk of collision. That test ... encourages a collision to ensure that when a collision occurs, your code ensures the names are unique. If you're relying on random values being unique, you shouldn't. This test exposes that.

**Comment by astrieanna** [comment]
But it says:
> Your solution must ensure that every existing robot has a unique name.

If my robot has been reset, then its name is not in use. So it should be able to generate the same name, shouldn't it?

**Comment by IsaacG** [comment]
> The next time you ask, that robot will respond with a new random name.

When you reset, the name must be different from the prior name.

When you generate a name, you must ensure it's not in use.

**Comment by BethanyG** [comment]
Hi @astrieanna 👋🏽 

[This issue](https://github.com/exercism/problem-specifications/issues/1937) and its related ones in [problem specifications](https://github.com/exercism/problem-specifications) might be of interest to you.  Problem specifications is the repo where we keep cross-track specifications for **practice exercises**, and discuss changes to them.  Tracks then pull from problem specifications to implement these exercises in a language-specific manner.

`Robot Name` has had some discussion recently due to its ambiguity (_you are not alone in your confusion!_).  I would suggest adding your comments/suggestions to the issue.  I believe we may be re-writing or re-working the exercise at some point in the near future.  

Unfortunately for now, @IsaacG comments are correct for the tests as currently written.

**Comment by astrieanna** [comment]
Thanks! I'll move over to the problem specifications instead.
