### ISSUE TITLE
Tisbury Treasure Hunt: Inconsistent quotes used in exercise 5 

### ISSUE THREAD

**Issue by jlim0159** [exercism/python#2919]
In the provided sample for the exercise (shown below), only single quotes appear in the final returned string. However, the expected answer used in the test also has double quotes inside of it. More precisely, double quotes are used to wrap the location name in the first tuple.
>  "Scrimshaw Whale\'s"

I guess that the reason for this is because there is already a single quote used in that particular location name and thus it would probably be nicer if it was wrapped with double quotes. However, this seems more like a bug and I was quite confused when the test failed. The problem also didn't specifically say anything about when to use double quotes instead. To get the test to pass, we have to separately handle the first tuple, which also doesn't seem like the point of the exercise.

```
>>> clean_up((('Brass Spyglass', '4B', 'Abandoned Lighthouse', ('4', 'B'), 'Blue'), ('Vintage Pirate Hat', '7E', 'Quiet Inlet (Island of Mystery)', ('7', 'E'), 'Orange'), ('Crystal Crab', '6A', 'Old Schooner', ('6', 'A'), 'Purple')))

"""
('Brass Spyglass', 'Abandoned Lighthouse', ('4', 'B'), 'Blue')\n
('Vintage Pirate Hat', 'Quiet Inlet (Island of Mystery)', ('7', 'E'), 'Orange')\n
('Crystal Crab', 'Old Schooner', ('6', 'A'), 'Purple')\n
"""
```

**Comment by BethanyG** [comment]
Hi @jlim0159 👋🏽 

Thanks for filing this issue.   

> I guess that the reason for this is because there is already a single quote used in that particular location name and thus it would probably be nicer if it was wrapped with double quotes.

**Your guess is correct:**  the reason Python supports both double quotes and single quotes for strings is exactly this scenario. 

 _But there is a further complication here:_  The expected result is a multi-line string that is wrapped in triple **double quotes** (_so that we don't have to escape all those single quotes from all the tuples_).  Changing  `"Scrimshaw Whale's"`  to  `'Scrimshaw Whale\'s'`  then causes a failure when the tuple content is concatenated into the triple double-quoted string because there is an unneeded `\` in it.  Since the latter scenario with the slash is even more confusing than the double quotes, we went with the double quotes -- especially since our basics and string exercises emphasize that Python will take either quoting style as needed, and that escaping via `\` should only be used when absolutely necessary.

<br>

>  To get the test to pass, we have to separately handle the first tuple, which also doesn't seem like the point of the exercise.

I don't have your code in front of me, but there shouldn't be any "special handling" of the first tuple needed.  As described in the exercise, `tuples` can be indexed into -- as can any other `sequence` type -- which was part of the point of the exercise.   So the solution for the final task can be handled by looping through and concatenating or f-stringing each item by index:

```python

def clean_up(combined_record_group):
    """

    :param combined_record_group: tuple of tuples - everything from both participants.
    :return: tuple of tuples - everything "cleaned". Excess coordinates and information removed.
    """

    report = ""

    for item in combined_record_group:
        report += f"{(item[0], item[2], item[3], item[4])}\n"

    return report

```

Does that make sense?  I hope so.  If not, please reply -- and we can work through it.  😄   I might also consider just renaming that first item so there is no `'` in it -- if it continues to be problematic.

**Comment by jlim0159** [comment]
I'm sorry I forgot to check for replies.

Whoops, my bad. I didn't think of this solution. Yeah, now this makes more sense :facepalm:. I think it might be better to keep it as it is. I didn't think that the formatter would deal with it for me. Really sorry for the trouble.

However, I think the argument for escaping the single quote isn't really valid because there isn't a need to escape it in the first place right? But this is just me nitpicking.
