### ISSUE TITLE
Guido's Gorgeous Lasagna - Python Error 

### ISSUE THREAD

**Issue by tsikmartin** [exercism/python#2955]
ImportError while importing test module '.mnt.exercism-iteration.lasagna_test.py'.
Hint: make sure your test modules.packages have valid Python names.
Traceback:
.mnt.exercism-iteration.lasagna_test.py:6: in <module>
    from lasagna import (EXPECTED_BAKE_TIME,
E   ImportError: cannot import name 'EXPECTED_BAKE_TIME' from 'lasagna' (.mnt.exercism-iteration.lasagna.py)

During handling of the above exception, another exception occurred:
.usr.local.lib.python3.9.importlib.__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.mnt.exercism-iteration.lasagna_test.py:23: in <module>
    raise ImportError("In your 'lasagna.py' file, we can not find or import the"
E   ImportError: In your 'lasagna.py' file, we can not find or import the function named 'EXPECTED_BAKE_TIME()'. Did you mis-name or forget to define it?

**Comment by BethanyG** [comment]
Hi @tsikmartin --

Could you please provide some more information on what you need help with?  Are you stuck on the error, or do you think you've received the error by mistake?  Without further detail, it is a bit difficult for me to help you fully.

If you are confused as to why you are getting an error -- the reason is noted on the last line of the stack trace:

**` ImportError: In your 'lasagna.py' file, we can not find or import the function named 'EXPECTED_BAKE_TIME()'. Did you mis-name or forget to define it?`**

Did you define a function named `expected_bake_time()` in your solution?  If not, the test runner will be unable to import your code and test your solution properly.

Please let me know if that helps - and what other issues I can help you with.  💛

**Comment by tsikmartin** [comment]
ahhh okay. i was working bit by bit, hoping it would give me something if i started from the top down and check my answers as i go. Did not realize i needed to complete the whole thing to check a part of my answer.

**Comment by BethanyG** [comment]
>  _hoping it would give me something if i started from the top down and check my answers as i go. Did not realize i needed to complete the whole thing to check a part of my answer._

You don't need to!  If you use the [stub file](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/lasagna.py).  I think the expected function names are in the comments.

If you define the function names and use the keyword `pass`, you should be able to run the tests without import errors and see all of the failures -- so that you can get a start on what the tests expect, and fill things in as you go.  Here's an example:

```python
EXPECTED_BAKE_TIME = 0
PREPARATION_TIME = 0

def bake_time_remaining():
    """Calculate the bake time remaining.
    :param elapsed_bake_time: int baking time already elapsed.
    :return: int remaining bake time derived from 'EXPECTED_BAKE_TIME'.
    Function that takes the actual minutes the lasagna has been in the oven as
    an argument and returns how many minutes the lasagna still needs to bake
    based on the `EXPECTED_BAKE_TIME`.
    """
    pass

def preparation_time_in_minutes():
    pass

def elapsed_time_in_minutes():
    pass
```

Running that against the tests should give you failure message for most or all of them.  Then, you can fill in the bits as you go and see which tests begin to pass.

**Comment by tsikmartin** [comment]
ahhhh perfect!!! thank you so much!!!!

**Comment by kgwaggo** [comment]
great
