### ISSUE TITLE
Add VS Code test runner files

### ISSUE THREAD

**Issue by jdkang** [exercism/python#2969]
It feels like it would be useful for CLI users to include a default `.vscode/settings.json` with each exercise.

e.g
```
{
    "python.testing.pytestArgs": [
        "."
    ],
    "python.testing.unittestEnabled": true,
    "python.testing.pytestEnabled": true
}
```
For VS Code users, this would mean it would be extremely straight forward to pull down the exercise locally, run tests, and then submit.

**Comment by kotp** [comment]
I would vote against it, as it opens the door for adding other personal choice things.

**Comment by BethanyG** [comment]
Hi @jdkang 👋🏽 

Thanks for filing this.  😄   As @kotp said above, if we did this for VS code, we'd _immediately_ have requests for 20+ other IDES and editors .... across _**56 different programming languages**_, each with their own test runner and test format.  😱   I don't think the team working on the [CLI](https://github.com/exercism/cli) wants to take that on. 

But there **are** ongoing discussions around documenting the [exercism api](https://github.com/exercism/exercism/issues/4087), which is public but not documented.  Which would allow for projects like [this one](https://marketplace.visualstudio.com/items?itemName=masonliu.exercism) in the VS Code Marketplace.  (_I went to see if the repo could be forked for that project, but it appears to have been removed, so I don't know that that plugin still works._)

So if you wanted to, you could make a VS Code plugin yourself using the API.  😄  -- or find some collaborators to work on it with you.

Additionally, we could look at adding to the [help documents for this track](https://github.com/exercism/python/tree/main/docs), describing how to "trick out" VS Code so that downloading exercises and running tests could be automated....if you are in the mood to submit one or more PRs.  😉

**Comment by BethanyG** [comment]
I am going to go ahead and close this issue.  @jdkang -- should you want to spike a VS code plugin or alter the track documents, please feel free to either re-open this issue, or create a new one.  Should you want to add information to the help documents for the track, we'd warmly welcome a pr.  😄
