### ISSUE TITLE
[Twelve Days] Instructions are unclear as to what the function should return.

### ISSUE THREAD

**Issue by clziegler** [exercism/python#2983]
What does it mean to "output the lyrics?" There is no indication that the output should be a list, or that the verses should be items of said list. The only way to find this is to look at the tests.

A pre-added docstring for the `recite()` function could be helpful.

for example:
```python
def recite(start_verse, end_verse):
    """Outputs verses from the song 'Twelve Days of Christmas'
   

    Args:
       start_verse (int): The verse number to start from
        end_verse (int): The verse number to end

    Returns:
        list: A list of strings from the first_verse up to and including the end_verse


    """
```

**Comment by BethanyG** [comment]
Hi @clziegler 👋🏽 

Thanks for filing this issue.  

For [Practice exercises](https://exercism.org/docs/building/product/practice-exercises), we give very minimal stubs.  The 'ethos' behind this is that practice exercises are implemented as a form of [test driven development](https://www.agilealliance.org/glossary/tdd/#q), where we've written out the core tests for you ahead of time.  You **_should_** be looking at the tests to get a feel for what is expected, and you should let test failure guide what you write in code.

Practice exercises (in contrast to the "learning" or [Concept exercises](https://exercism.org/docs/building/product/concept-exercises))  are meant to encourage practice with multiple techniques in the language and/or algorithms or design decisions.  Implementation is much less directed, problem descriptions are less detailed (_and are mostly shared across tracks_) and the test files tend to look for outcomes, and shy away from dictating data structures (_where that's possible_).  Often students will discuss with mentors different approaches, and may even add their own additional test cases locally as they work through the problem.

So while I agree that the requirements of Twelve Days are indeed frustrating (_it is not one of my favorite exercises_), we're not likely to add docstrings or typehinting for them.  We leave those additions to the student, as they work through the requirements and test failures and refactor their code.

Where a problem is truly obscure or written in a confusing manner, we do add hints or even an instruction addendum, but I don't think that those are needed here, since the tests are pretty clear on what is expected (_once you understand that they are using implicit string concatenation_).

**Comment by BethanyG** [comment]
Since it's been a few days, I am going to go ahead and close this issue.  Please feel free to re-open it or file a new issue, should you want to add hints or discuss the structure of this exercise further.  Although the specification for this exercises is pulled from the central [problem specifications](https://github.com/exercism/problem-specifications), so it's best to bring up overall design issues there.  This repo is for the Python-specific implementation.
