### ISSUE TITLE
Clock recommended after 10 solved exercises

### ISSUE THREAD

**Issue by StevenBontius** [exercism/python#2985]
Hi, I really like this project but I think there is a small issue with the recommended exercises.

Clock was recommended to me after I've solved just 10 exercises . Besides the fact that concept is still locked, it is way to difficult for people to solve who just started.

**Comment by BethanyG** [comment]
Hi @StevenBontius 👋🏽 

Thanks for filing this issue.  I agree that `Clock` is probably not something you want to take on after just 10 exercises.  Not entirely sure how the recommendation happened, since `Clock` isn't even linked in the (_currently_) active syllabus tree.  

My _suspicion_ is that it unlocked because it only has three prerequisites - `basics`, `numbers`, and `strings` - so once you completed those concepts, it went into the pool of "available" exercises, and thus got recommended.  We've since added a concept exercise on `classes` that should be part of the prerequisites.  I will be adjusting the track config accordingly, and that might  help things a bit.  Additionally, we're looking at the "level" of each of our practice exercises.  I'll note that maybe `Clock` needs a "bump" in difficulty level.

**Comment by StevenBontius** [comment]
Thanks @BethanyG
