### ISSUE TITLE
K-means clusters using raw python  

### ISSUE THREAD

**Issue by SSahas** [exercism/python#2999]
Hello, I am Sahas. I wanna create a python problem which is implementing k-means clusters algorithm using raw python. please tell me if this is considerable or too much for an exercise or it requires any changes.

K- means Algorithm :  The K-means clustering algorithm computes centroids and repeats until the optimal centroid is found. It is presumptively known how many clusters there are. It is also known as the flat clustering algorithm. The number of clusters found from data by the method is denoted by the letter 'K' in K-means.

![clusters gif](https://user-images.githubusercontent.com/82393353/161542858-9c4c1307-5f25-4cd6-93dd-14e4ce3b8dc2.gif)
.

The code is available here :  

[SSahas](https://github.com/SSahas)
/
[exercism-problem](https://github.com/SSahas/exercism-problem)

The code Mainly uses : 

  - Dictionaries 
  - Nested for loops

**Comment by BethanyG** [comment]
Hi @SSahas 👋🏽 

Thanks for filing this issue, and for stepping forward to (possibly) design an exercise for Exercism!

**`TL;DR`:**  Specifications for [practice exercises](https://exercism.org/docs/building/tracks/practice-exercises) and specifications for [concept exercises](https://exercism.org/docs/building/tracks/concept-exercises).  Additionally, we use `pytest` as a runner for the track, so all tests would need to use `unttest` syntax, and be runnable via `pytest`.  For additional considerations, see the [Python Contributing Docs](https://github.com/exercism/python/blob/main/CONTRIBUTING.md).

While having an algorithm implementation like this might be interesting,  I do have some concerns:

1.  This is an implementation of the algorithm with sample data, but to be meaningful to students we've found that _solving a specific problem_ is more engaging and leads to better learning.  `K-means` can be used for spam filtering, fraud detection, audience segmentation, signal processing, image segmentation, and recommendations - among other things.  What problem would you center this on, and what would the data and problem statement for it look like? 

2. This isn't "pure Python" or "raw Python" in a "traditional" sense -- your implementation uses `Numpy`, `Pandas`, `Jupyter` and `Matplotlib`.  That isn't _bad_ -- but it does mean the use of libraries beyond the Python standard lib.  Since current exercism tooling for the website only supports core Python, we'd need to do some work to support the loading of external libraries such as `numpy` and `pandas`.  And even with that work, we wouldn't support the use of `Jupyter Notebooks` or `JupyterLab` (_they include a whole web stack and other complex considerations_), and might not be able to support `matplotlib` in a very effective way, due to its visual nature.

3. In addition to website tooling, we have the issue of walking students through what they would need to set up to work on the problem via the CLI.  There are certainly ways to do this, but it is additional work.

4. Running the steps of `K-means` repeatedly to reach optimum partitioning may not fit within the performance needs of our current platform.  We'd need code and tests to execute  in a maximum of ~10s before timing out. There are also the cases where a `k-means` implementation never reaches optimum, so we need to be careful of that in the construction of the data set.

5. K-means partitioning is not deterministic.  Outcomes vary depending on the amount and position of the starting centroids and the number of iterations the algorithm goes through.  That presents some challenges for student verification, testing, and feedback.  I'd want to see what tests looked like for this problem, and run them over multiple solutions before we released anything on the platform/to students.

6. As it stands now, this isn't a _programming_ or _algorithm_ challenge as much as it is one of deciding how to _apply_ or tune `k-means`.  It also feels as though we'd have to point students at a lot of "prep" documentation, or have a lot of explanation as a set up to this coding challenge.  While I am not opposed to a `ML` or `Data Science` branch for the Python track, I don't know that I would _start_ with `k-means` as a first problem, so I'd want some background from you on where you see this problem fitting into the current Python track, and what the supporting documentation/explaination for it would look like.


I also think that the `R`, `Julia`, `C`, `JS`, `Ruby` and `Go` languages (among others) have some pretty powerful tools for both `ML` and `data science`, so limiting this problem to a Python-only implementation feels wrong to me.  So I think the best strategy would be to discuss this as a more generic [practice exercise](https://exercism.org/docs/building/tracks/practice-exercises), rather than a Python [concept exercise](https://exercism.org/docs/building/tracks/concept-exercises).

So - I am not saying no outright, but I would like some more details.  Looking forward to hearing them.  😄

**Comment by SSahas** [comment]
Hello @BethanyG,

Thanks for your Response 😄, 
I am glad you are showing interest, I am not so sure but  I will try to resolve this issues as soon as possible , but I cannot implement this algorithm in R, Julia, Ruby, C  , JS, Go etc. .. I have not learned this languages. so may be it should be a practice exercise.

**Comment by SSahas** [comment]
Hey @BethanyG,
I think this is hard , this will take time 😅.So i think we should stop this.

**Comment by BethanyG** [comment]
@SSahas  - I'll close for now.  But feel free to re-open, should you want to work on this!
