### ISSUE TITLE
[Gigasecond]: Suggestions Regarding Instructions

### ISSUE THREAD

**Issue by CodebyKhayla** [exercism/python#3018]
I repeat, this is not a bug. However, could the instructions for the Gigasecond exercise be edited for clarity? 

It is marked as easy, but links to material for Ruby not Python. 
Also, it would be helpful if it gave example inputs and outputs to help a beginner understand. 

Current exercise instructions: 
"_Given a moment, determine the moment that would be after a gigasecond has passed.
A gigasecond is 10^9 (1,000,000,000) seconds._"

**Comment by BethanyG** [comment]
Hi @CodebyKhayla 👋🏽 

Thank you for filing this issue.  Where are you seeing links to Ruby material?  I'm not seeing any in the instructions themselves - were you looking at a hint file or other element in the UI?  

If you could provide a screen grab, that would be super-helpful in me tracking down the issue (_different parts of the UI are pulled from different files_).  While this isn't a _bug_ per se, we do want to make sure that we keep reference materials for different programming languages separate to avoid confusion.

> Also, it would be helpful if it gave example inputs and outputs to help a beginner understand.

We practice a form of Test Driven Development (_TDD for short_) on exercism, where we provide the main tests for you.  [TDD](https://www.agilealliance.org/glossary/tdd/) has you write tests _before_ code, to allow test failure to guide the implementation.  So we expect students to look at the [test files](https://github.com/exercism/python/blob/main/exercises/practice/gigasecond/gigasecond_test.py) to figure out what the expected inputs and outputs of their functions should be.  Here is an example of a failed test in the website for `Gigasecond`:

![2022-04-21_09-51-06](https://user-images.githubusercontent.com/5923094/164511148-966d6d43-25a2-456b-a32a-c104fe0def42.png)

So based on the expected output, a student should be parsing a `datetime` object, adding a gigaseconds worth of time to it, and then returning the result as a `datetime` object.  Which is "easy" when you use a `timedelta`.

But that being said, this exercise is only easy if someone knows about the [datetime](https://docs.python.org/3.9/library/datetime.html#module-datetime) library in Python.  And more specifically, [`datetime.datetime`](https://docs.python.org/3.9/library/datetime.html#datetime.datetime) and [`timedelta`](https://docs.python.org/3.9/library/datetime.html#timedelta-objects) objects.

So I am going to PR a Python `instruction append` to point that out, and maybe also add a `hints` file with some additional links on how to use `datetime` in Python.

If you are up for it, I'd also be happy to walk you through how to make a PR for one or both of those documents, if you'd like to help improve this exercise.  Just let me know.  😄

**Comment by CodebyKhayla** [comment]
@BethanyG, 

Thanks for the information! it definitely helps to understand the methodology behind the exercises. 

I guess from my viewpoint as being new to the site and somewhat new to Python (with only beginner experience in another language), I'm completing the Python track (as we speak, I'm 0.8% complete it lol). This is one of only 3 exercises that are available for me to try. Even with the feedback from the test files, I don't understand how to read them. I'm quite new to this. Even googling documentation/articles was an unfruitful exercise.  

It is not really easy from that perspective, as it is written now. I understand that the code in the answer to the exercise question may not be complex, however, there are other things that go into an exercise that determine its level of complexity, right?  


To answer you question, I was referring to the source document linked in the instructions. 

![image](https://user-images.githubusercontent.com/44632276/164545501-937ce8b5-4e98-4dd9-954c-c08fbf5e3bc9.png)

the source material link opens to: http://pine.fm/LearnToProgram/?Chapter=09 

I think since there is the expectation to rely on the testing process to help guide learning, if there was even a little '?' button/link to somewhere briefly explaining Exercism's methodology as you have just now explained and maybe a little guidance on how to read the tests and how to use them in general as support in learning programming and/or links to Python-relevant source material would be helpful in making this an actual 'Easy' exercise that a beginner could do. 

As to your suggestion about adding documents about datetime and making a PR, I would absolutely love to learn how to do that! But, I'm also open to whatever's easiest for you.

**Comment by BethanyG** [comment]
@CodebyKhayla 

> This is one of only 3 exercises that are available for me to try. 

I need to examine why `Gigasecond` is showing up when you have learning mode on and have not yet completed `Guidos Gorgeous Lasagna`.  You should have different exercises available to you.  Consider it on my `todo` list!

<br>

> It is not really easy from that perspective, as it is written now. I understand that the code in the answer to the exercise question may not be complex, however, there are other things that go into an exercise that determine its level of complexity, right?

I wholeheartedly agree!  And just to be clear:  we never intended for this to be one of three exercises a brand-new user sees when they start Python, so I will definitely be investigating that.  There are many other exercises on the track that don't require knowing a specific module, so we're better showing those to students over this one, which requires more specialized knowledge.

<br>

> To answer you question, I was referring to the source document linked in the instructions.

Ah!  Yes - that is pulled from a different file, and is there to make sure we give credit to the people who originally designed this exercise -- it wasn't meant as documentation.  The exercise was originally designed for Ruby (_we adapted it for other language tracks_), and I can see how having such short directions for Python followed by source a link sets up a scenario where students click through expecting a how-to or other details.  Clearly, there needs to be a Python-specific addendum here.  😄 

<br>

> I think since there is the expectation to rely on the testing process to help guide learning, if there was even a little '?' button/link to somewhere briefly explaining Exercism's methodology as you have just now explained and maybe a little guidance on how to read the tests and how to use them in general as support in learning programming and/or links to Python-relevant source material would be helpful in making this an actual 'Easy' exercise that a beginner could do.

Wholeheartedly agree with this as well.  We do have general Python-track docs, but they are a little hard to find on the website.  Here is a link: https://exercism.org/docs/tracks/python.  They don't currently have anything on TDD or reading Python test files -- but I will put together an issue about it. I can ping you when I have a draft ready, if you'd like to collaborate on what we'd put in the doc?  It would be a good edition to our docs, I think.  Exercises also have `hints` files, which can be accessed via a 💡  icon:

![2022-04-21_15-11-52](https://user-images.githubusercontent.com/5923094/164560842-7719874f-6f14-4b09-a996-c84fb5fb61d1.png)

which brings up a modal with hints for the exercise (when available, which they are not for many exercises).  We could consider then linking to the TDD file from there for students as well.

![2022-04-21_15-12-13](https://user-images.githubusercontent.com/5923094/164560912-a36a0cda-c0ce-48ac-9978-2e9d36caec90.png)

 
> As to your suggestion about adding documents about datetime and making a PR, I would absolutely love to learn how to do that! But, I'm also open to whatever's easiest for you.

I would be delighted to help you with a PR for `hints` and or and `instructions.append`!  I will put the steps in a follow-on comment, since this is getting long.   😄

**Comment by BethanyG** [comment]
There are a few ways you can create a PR.  I am going to assume you are new to both git and GitHub, so apologies if this is overly-explanatory.

- Our general guidelines for PRs are [here](https://exercism.org/docs/building/github).  I'll include more detailed links for GitHub and Git below.
- Exercism uses [markdown](https://www.markdownguide.org/) for text documents.  Our guides for markdown and style are [here](https://exercism.org/docs/building/markdown).
- GitHub has a [QuickStart Guide](https://docs.github.com/en/get-started/quickstart) that can walk you through the general process of forking, branching, updating, and creating a Pull Request.
- At the bottom of that table of content is a link to [Git and GitHub learning resources](https://docs.github.com/en/get-started/quickstart/git-and-github-learning-resources), which is quite helpful, as is the [GitHub Learning Lab](https://lab.github.com/)
- Additionally [this FreeCodeCamp](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) walkthrough is helpful. 
_____

To do this on your computer locally, you'll need an installation of `git`, a fork of this repo, and your favorite code editor.   Once you have  a local branch, you'll need to create the following two files under `https://github.com/exercism/python/tree/main/exercises/practice/gigasecond/.docs/`:

1.  `instructions.append.md`.  
      -  This document is where you would add a Python-specific set of instructions for the exercise.  [Here](https://github.com/exercism/python/blob/main/exercises/practice/clock/.docs/instructions.append.md) is an example of what an append can look like.  It doesn't have to be that long, but it does need to have the top level `#Instructions append` header. The addendum will end up appearing in the UI above the **source** link, and below the general instructions.  Here is a screengrab of what that looks like for our `Clock` exercise:

<img src= "https://user-images.githubusercontent.com/5923094/164565108-2394ca93-90d4-44f0-90e5-e386e1cef45f.png" height= "400" />


2. `hints.md`.
     -  This document is where you would add Python-specific _hints_.  These would be similar to what is in [this file](https://github.com/exercism/python/blob/main/exercises/practice/darts/.docs/hints.md) for the `Darts` exercise.  Hints right now both require the `# General` header, and each should be a _bullet_.  They should also _hint at_ but not give away the direct solution to the problem.  Links to tutorials or documentation is great -- just not a direct _answer_ if that makes sense.  Hints display as per the two screengrabs I made in the comment above.

Once you have the two files done to your liking, you will need to commit the changes and push them to your forked repo on GitHub.  From there, you can open a PR to this repo, which will trigger the CI and a request to reviewers to look it over.
_________

As an alternative to doing the changes on your computer, you **can** do them through the GitHub interface.  I wouldn't recommend doing that for anything that is long or code-related, but it can be fine for shorter documents like these.  To do that, you would go to your fork of the repo and make a new branch:

![2022-04-21_16-22-34](https://user-images.githubusercontent.com/5923094/164566939-cd2e6c39-02f4-4321-8a00-29d27eb92737.png)

Once that's done, you can navigate to the directory, and select `create file`:

![2022-04-21_16-23-36](https://user-images.githubusercontent.com/5923094/164567003-7d96e911-f845-4388-8046-ce520b0f7d8e.png)

Once you have typed in a file name, the UI will allow you to click directly into the `edit` tab and write markdown:

![2022-04-21_16-27-58](https://user-images.githubusercontent.com/5923094/164567161-69c947eb-d0ec-4e2d-bc46-7c89aab05be1.png)

Once things are done, you can commit the file at the bottom of the page:

![2022-04-21_16-28-59](https://user-images.githubusercontent.com/5923094/164567238-55b0f583-cd1c-4e74-b193-b0df3f9927a6.png)

From there, you can open a PR on this repo.
_______________

A  third way to go through this process is to use the [GitHub Desktop](https://desktop.github.com/) client or the CLI.  Eventually, it's best to learn `git` for development, but it doesn't have to happen _right now_.  😄 

___________

For instruction append, I'd recommend something along the lines of:

 "The implementation of this exercise in Python is designed for you to learn and practice using objects from the [`datetime`](https://docs.python.org/3.9/library/datetime.html#module-datetime) module.  To that end,  the tests require you to accept a `datetime` object as input, add a gigaseconds worth of time to it, and return the resulting `datetime` object as output.  
- [`datetime`]() in Python
-  [`datetime.datetime`]() objects
-  [`dtatetime.timedelta`]() objects
-  [Using Python datetime to work With Dates and Times](https://realpython.com/python-datetime/)"

But as a learner, you have more insight than I do - so that's just a starting point.  You could add more or something different.  It shouldn't get too prescriptive though, and it should probably be shorter than that Clock one I showed as an example.

Alright.  I hope I haven't scared you away or put you to sleep with the long long essay.  Let me know if you have any questions or issues - and I look forward to seeing what you come up with for the two docs!  Thanks again for your issues and your patience.  ⭐ 🌈

**Comment by CodebyKhayla** [comment]
> We do have general Python-track docs, but they are a little hard to find on the website. Here is a link: https://exercism.org/docs/tracks/python. They don't currently have anything on TDD or reading Python test files -- but I will put together an issue about it. I can ping you when I have a draft ready, if you'd like to collaborate on what we'd put in the doc?

Yes. I would love that.

**Comment by BethanyG** [comment]
Making note here about keeping this issue open. While the `hints` file and the `instruction append` have been added (YAY), I still need to make and issue around TDD docs, so leaving this as a reminder to do so.

**Comment by BethanyG** [comment]
Hi @CodebyKhayla 👋🏽  

 _apologies for the delay in getting back to you!_  I've opened a new issue around Test Driven Development, and would love any additions you'd like to chime in with.  😄   You can find the issue [here](https://github.com/exercism/python/issues/3053).  We've got a contributor who's thinking about drafting something up, so keep your eyes out for that when it happens.  Meanwhile I am going to close this particular issue as resolved.

Thank you so much for logging this, for your willingness to discuss things..and for your PR!  😄   _We very much appreciate it!_ 🌈

**Comment by BethanyG** [comment]
reopening as a brief test.
