### ISSUE TITLE
[Twelve Days] Instructions are too vague

### ISSUE THREAD

**Issue by ViniSalvon** [exercism/python#3031]
In [this exercise](https://exercism.org/tracks/python/exercises/twelve-days), the overall instructions are not clear. For example:

- If I take the instructions alone in a literal way, a simple return or print with the string containing the whole lyrics would actually be a solution. However, when you begin the test, it shows you a function that receives a start and an ending verse. While it is intuitive, I think that this part should be in the instructions set.

- Even when you take that into account, it is not clear how the output should be. Does it want a function that returns something (a whole string containing the text, I suppose. Or would it be a list?)? Or maybe I should just print the lyrics?

- Still on the output formatting, let's say it is a string. How should be the text? Does it requires new lines between verses? Simple new lines or double new lines? What about new lines between gifts?

It's not clear, because if you take the text in the instructions, it's asking for a "empty line between verses + no newlines inside a whole verse = gifts in the same line", while in the tests, it seems that the program is expecting a new line between each gift of a verse.

Since the instructions are evidently incomplete, in my opinion it should be rewritten to match whatever the tests are requiring. But since I'm somewhat new to exercism, if I actually missed something, please give me your feedback.

**Comment by BethanyG** [comment]
Hi @DarkCyborg00 👋🏽 

Thank you for filing this issue!  

The current directions are indeed ... vague.  They were actually updated recently in our [problem specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/twelve-days/description.md), but we didn't get around to updating the Python version until now.  Apologies for that!  You can find our update in PR #3032, which should be merged shortly. 

However, the directions were never intended to specify the detail that is in the attached test file.   

We we practice a form of Test Driven Development (*TDD for short*) on exercism, where we provide the main tests for you (_rather than have you write the tests yourself_). 

[TDD](https://www.agilealliance.org/glossary/tdd/) practice has you write tests *before* code, to allow test failure to guide the implementation. So we expect students to look at the [test files](https://github.com/exercism/python/blob/main/exercises/practice/twelve-days/twelve_days_test.py) to figure out what the expected inputs and outputs of their functions should be.

That being said, `Twelve Days` is a bit problematic - as the note on top of the test file states, the tests employ [implicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining), removing the need for the student to include a `\n` at the end of each verse. That can be really confusing if a student has not encountered it before.  It is also not clear at first that the expectation is that a `list` of verses should be returned (_from the `start` to `end` parameters for the `recite` function._) .  Additionally, if a student hasn't encountered a repeating/additive song like `Twelve Days` before, it can take a while to figure out what is going on _within_ each verse, and for multiple verses. 

I'll think a little bit about possibly making a Python instruction append for this exercise, and what that append might look like.  I'll also think through a possible `hints` file to help really confused students out.  Although with both files, I would want to be pretty careful of content, since the bulk of this problem is finding the repeating pattern in the verses, and building and returning them efficiently.  We don't want to over-specify and turn this into a basic string concatenation problem.

I'll ping back with drafts of both docs, so you can review and see if they clarify things.  Conversely, if you would like to a submit a PR for both docs, I'd be happy to review/walk you through making them.  Just let me know.

**Comment by BethanyG** [comment]
Closing now that #3050 has been merged.

**Comment by BethanyG** [comment]
@ViniSalvon 😱   _apologies._ I promised I would ping back, and forgot to do so.  Please see the merged PR above for the changes we've made to Twelve-days.  Please feel free to log an additional issue or PR to add to those changes if you fee they are lacking in any way.  Thanks again for filing this issue!
