### ISSUE TITLE
Python permissionerror: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by shjustinzhang** [exercism/python#3129]
Hi Guys, I have a question, although I have already get it fixed, but I don't know why, I hope your guys can get the bottom of that.

The case is as long as I move under path "c:/", I will get permission denied, and I get into "c:/Users/juntizha/Python example" to run the script, don't have issue, do you know why ?

OS Env : Win 10
python : 3.10.2

PS C:\Users> & C:/Users/juntizha/AppData/Local/Programs/Python/Python37/python.exe "c:/Users/juntizha/Python Example/simple1.py"
c:/Users/juntizha/Python Example
c:\Users\juntizha\Python Example\simple1.py
Traceback (most recent call last):
  File "c:/Users/juntizha/Python Example/simple1.py", line 48, in <module>
    f = open("db.ini", mode="w", encoding="utf-8")
PermissionError: [Errno 13] Permission denied: 'db.ini'

PS C:\Users\juntizha\Python Example> & C:/Users/juntizha/AppData/Local/Programs/Python/Python37/python.exe "c:/Users/juntizha/Python Example/simple1.py"
c:/Users/juntizha/Python Example
c:\Users\juntizha\Python Example\simple1.py
c:\Users\juntizha\Python Example
c:/Users/juntizha
C:\Users\juntizha\Python Example\sampl
---------------------------
c:\Users\juntizha\Python Example\simple1.py
C:\Users\juntizha\Python Example\db.ini

**Comment by BethanyG** [comment]
Hi @shjustinzhang 👋🏽 

This repo is for the Python track content of exercism.org.  Your question appears to be related to more general Windows / Python permission problem or configuration problem on your machine and is out of scope for this repo.  Consequently, I will be closing it.

That being said, based on the paths you have posted, your issue could be related to one or more of the following:

1. Windows, and posix operating systems have differences in how they model [paths](https://docs.python.org/3/library/os.path.html).  This can create issues when a path is needed to perform an action like `open`, and the errors can be confusing.  This [stack overflow](https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied) post has good information on how to mitigate that.
2. `C:/Users/juntizha/AppData/Local/Programs/Python/Python37/python.exe` is the path to **`Python 3.7`**, not `Python 3.10.2`, so you should confirm that `Python 3.10.2` is what is being called when you invoke `python` to run a script, otherwise the two versions might be creating some sort of conflict or permissions problem. Suggest that if you wish to use two or more versions of Python on the same machine that you create [virtual environments](https://docs.python.org/3/library/venv.html) to do so.
3. You should verify that the `Python 3.10.2` you have installed on your machine has the correct permissions for what you are intending to do.  There have been [reports](https://stackoverflow.com/questions/65785745/permissionerror-errno-13-permission-denied-on-windows) in the past of Python installations on Windows not having the correct permissions when installed, so you might consider re-installing `Python 3.10.5` from [the PSF](https://www.python.org/downloads/release/python-3105/).  
4. Your script (or Python) may not have all the appropriate permissions to write to logging, execution, or configuration directories.  That can cause permissions errors.  This [stack overflow](https://stackoverflow.com/questions/66596574/the-error-is-permissionerror-errno-13-permission-denied-c-programdata-m) post covers some of the common issues and mitigations.
5. Finally, [This article](https://itsmycode.com/python-permissionerror-errno-13-permission-denied/) covers multiple probable causes for getting a `permission denied [Errno 13] error when working with Python, so might be a handy troubleshooting list to refer to.

**Comment by shjustinzhang** [comment]
Thank you.

Yeah, my bad, I install python 3.7 and python 3.10, on this script, I need to use python 3.7, sorry for the wrong information about python version.

Your script (or Python) may not have all the appropriate permissions to write to logging, execution, or configuration directories. That can cause permissions errors. This [stack overflow](https://stackoverflow.com/questions/66596574/the-error-is-permissionerror-errno-13-permission-denied-c-programdata-m) post covers some of the common issues and mitigations.
-> this is valuable.

Appreciate once more.
