### ISSUE TITLE
[Ghost Gobble Arcade Game]: Wrong param docstring description.

### ISSUE THREAD

**Issue by MultiP-Dev** [exercism/python#3149]
Looking at the instructions and the parameter name itself, it looks like the docstring for the param touching_power_pellet on the score() function should be changed to "is the player touching a power pellet?" instead of "does the player have an active power pellet?" 

I initially opened a pull request to fix this issue but I soon realized any change that is not typo fixing should be discussed first via an issue, so I closed it. This is my first time contributing to Exercism and I'd be happy to open a pull request if it's ok.

**Comment by BethanyG** [comment]
Hi @MultiP-Dev 👋🏽 

Thank you for filing this issue!  I saw your PR yesterday fly by in my notifications, but did not have time to answer until now. 
You're right - the parameter name for `score()` in the stub is inconsistent with the question in the docstring.  We'd be happy if you'd PR the change.  😄  I think you might be able to re-open your closed PR from yesterday, if that makes things easier.

As an FYI for the future, we happily accept PRs that are not just fixes for typos -- as long as they are submitted for one exercises set of docs/files at a time, and the changes are both obvious and needed.  It helps to have a good PR description that lays out the logic of your changes, and commit messages that make clear what you've done.

What we're trying to avoid here are "changes for the sake of change" (_things that are a difference of opinion or small changes to language that are not clear improvements_) or large/time consuming changes that a contributor makes that may get rejected on review because they're not in line with the current state of the track. 

To avoid these scenarios, we often like to discuss the changes via a filed issue -- it helps us keep a discussion record and clarify what work is being/going to be done.

With all that being said, I look forward to reviewing your PR! 🎉   

I might also recommend giving this exercise's related documents (concept files [here](https://github.com/exercism/python/tree/main/concepts/bools) and exercise files [here](https://github.com/exercism/python/tree/main/exercises/concept/ghost-gobble-arcade-game) a once-over, to see if there are any other typos, details, or code examples that might need improvement.  If you find any issues, you could add those to the pending PR as well.  But you don't _**have to**_ do that unless you'd like to.  😉 

Please also ping if you have any questions or issues -- we're happy to help!  😄

**Comment by MultiP-Dev** [comment]
Thanks a lot for your thorough and friendly reply :)! I've created a new PR since I had deleted the fork previously. Looking at the related documents you mentioned, I've found a small typo and incorporated that into the PR also.
Happy to contribute!

**Comment by BethanyG** [comment]
Closing now that #3151 has been merged.  Thank you for your contribution, @MultiP-Dev!
