### ISSUE TITLE
[List Ops]: clarity about what operations we are permitted to use

### ISSUE THREAD

**Issue by scmbradley** [exercism/python#3154]
The instructions ask us to implement `map`, `filter` etc "without using existing functions.". But what does that mean? For example, `append` can simply be `return list1+list2` but that seems like cheating, and not in the spirit of the exercise. But which resources are we permitted to draw on and which not? It's not very clear what counts as a reasonable solution and what solutions are just cheating.

**Comment by bobahop** [comment]
It means to implement them without using the built-in functions. Those functions are described [here](https://book.pythontips.com/en/latest/map_filter.html). Other than that, use what makes sense to you. If the solution passes all the tests, and you'd like feedback, you can request mentoring.

**Comment by bobahop** [comment]
Of course, you may use other built-in functions: just not the ones that are essentially equivalent. For instance, "how would I get the length if the `len()` function were not available to me?" That would involve using a function other than `len()`; most likely something that would count up the elements of whatever you're getting the length of.

**Comment by scmbradley** [comment]
Thanks for the replies, but I think there still needs to be more clarity on what we can and can't use. For example, `append`can be implemented just with `list1+list2`: is that permitted? `reverse`is just `input_list[::-1]`is that OK? Are we allowed to use `range`? What about list methods like `append`? What about list comprehension? That makes some of the functions trivial to implement... 

There's maybe no hard and fast rules about what list of operations are "basic" or whatever, but it might help to have a bit more guidance.

**Comment by bobahop** [comment]
Thank you for the level of conscientiousness you're bringing to this.

What is "allowed" is real constrained by only two things.

What passes the tests is what is "allowed" by Exercism.

What level of challenge to accept is what is "allowed" by yourself.

So, even if `map` and `filter` were used here, Exercism would "allow" it.

But if you feel you don't learn enough by doing that, then try to figure out another way.

The direction to not use `map` and `filter` is really a suggestion for yourself. Exercism only requires that the tests pass.

Also, you should know that the instructions are inherited from the [problem-specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/description.md) repository, from which all language tracks derive. So, if this response leaves something you still want to address, you may want to open an issue at that level. If you do, please let us know so we can close this language-specific issue.

Thanks!

**Comment by scmbradley** [comment]
Happy to give something back, I've learned a lot from exercism.

I think the point about setting your own level of challenge is a helpful one, and perhaps we should say something like that in the instructions.

I think the issue is that python is a very expressive language, and this exercise is actually very easy if you can use python's slicing and list comprehension constructs. Perhaps the instructions could say: "for an additional challenge, try completing the exercise using only the following methods and functions..."  I don't really have a specific idea about which subset of functions would make this exercise interestingly challenging (but doable), but I thought it was worth opening up a discussion about it.

**Comment by bobahop** [comment]
Setting one's one level of challenge  applies to all exercises, so a place to make that more clear may be in the [Getting Started](https://exercism.org/docs/using/getting-started) doc for Exercism.

An issue with suggesting specific functions to solve an exercise is that Exercism doesn't want to give away a solution. It is up to the student to explore what approaches are available and to implement what they choose to pass the tests. After that, if the student would like to "know what they don't know" they can look at community solutions or request mentoring.

**Comment by BethanyG** [comment]
Hi @scmbradley 👋🏽 

Just chiming in here to say that since we've re-ordered the track, we have had a few questions on this particular exercise.  See #3142, #3141, and the related #[2078](https://github.com/exercism/problem-specifications/issues/2078) in  problem-specifications.  It is probably due for a little going over/revising.

As discussed in #2078, there are several avenues we could take in clarifying/filling out this exercise:

1.  An instruction append, along the lines of [this exercise](https://github.com/exercism/python/blob/main/exercises/practice/simple-linked-list/.docs/instructions.append.md) -- not that we have to be that imperative, but we can add a few instructions/variations.   As @bobahop noted in his replies, we probably don't want to do anything that might "give away" a specific solution, but we could always suggest/encourage thinking about certain modules, approaches, or functions in a hinty sort of way.
2.  A `hints.md` file, similar to the one for [this exercise](https://github.com/exercism/python/blob/main/exercises/practice/word-count/.docs/hints.md).  I especially like the opening paragraph that reminds the student that there are multiple paths/strategies.  We might outline useful groups of functions or modules at different "levels" of difficulty.  Again, these would probably be in the form of questions like _"how might **x** help you to not use the + operator here??"_ or _"could **y** help you out with this?"_
3.  A set of mentor notes (_see the [website-copy](https://github.com/exercism/website-copy/tree/main/tracks/python/exercises) repo for examples for Python_).  In the mentor notes, we could encourage mentors to nudge students to challenge themselves with one or more variations on the exercise.
4.  Some additional Python-specfic tests that nudge a student in a particular direction.  We'd want to be careful to not fish for a specific implementation, so this approach might be limited.


We'd welcome PRs connected to any of the above, and we'd be happy to help you through the PR process, if you'd like to take on any of the work.  Since we've gotten multiple sets of feedback on this exercise, I was thinking of consolidating the comments into one issue for tracking purposes.

Let us know if you'd like to take a shot at improving this exercise, and I can assign the consolidated issue to you!

**Comment by BethanyG** [comment]
@scmbradley  - closing this in favor of the tracking issue.  Please comment there if you would like to work on it and submit a PR.  Many thanks for filing this!
