### ISSUE TITLE
Solution hints not helpful.

### ISSUE THREAD

**Issue by oseghr** [exercism/python#3176]
Completed the solution but kept getting several warnings such below:

Line 12 [C0303 trailing-whitespace] : ["Trailing whitespace"] was reported by Pylint.
Which means this code doesn't follow general [code style](https://www.python.org/dev/peps/pep-0008/) conventions. While this type of issue generally doesn't affect the way code executes, it can hurt readability or the performance of automated tools such as documentation generators or test runners.

Even after following the PEP documentation and expecting the warnings to stop it didn't. Please could this be a bug?
The recommendation does not give an example of what the solution might look like.
![error](https://user-images.githubusercontent.com/37249148/194600659-d7924b0c-33ec-4315-8179-a565d562c742.jpg)

**Comment by BethanyG** [comment]
Hi @oseghr, 

Thanks for filing this issue.  When PyLint complains about "trailing whitespace", it is because there are excess "white space" (_non visible but present_) characters that are left at the end of lines of code.  Things like [tab] (`\t`) or [space] (`' '`) or [newline] (`\n`) or [carriage return] (`\r`). While these are not _fatal_, they can cause problems under certain circumstances.

They are particularly annoying because _you can't see them_, and they (mostly) get ignored ..... until they don't.

Did you paste your code into the online editor?  I often do that -- and it creates `\n` or `' '` at the ends of lines.  It's not catastrophic, but if you go through and delete them, the bot will stop complaining.  If you have done that already, then it may indeed be a problem with our analyzer -- in which case, we'll look at turning off the analyzer rule.

**Comment by BethanyG** [comment]
Closing as resolved/abandoned.
