### ISSUE TITLE
[Crypto Square] exercise is lacking a test for empty text after normalized

### ISSUE THREAD

**Issue by izmirli** [exercism/python#3178]
For exercise [Crypto Square](https://exercism.org/tracks/python/exercises/crypto-square) there is no test case for plaintext made up of just spaces and punctuation.

There are tests for normalized input - one for removing spaces, and one for removing punctuation, but not for the case text is empty after normalized. Mentored someone with code that pass all tests, but have a bug in this case, so wanted to add this.

I'm new to to **exercism** github contribute, so not sure about a lot of stuff... I saw in another issue that test maybe taken form **problem-specifications** repo, so I posted a PR there:
https://github.com/exercism/problem-specifications/pull/2129
But if test for Python track should be PRed here, please tell me.

My original intention was to update:
https://github.com/exercism/python/blob/main/exercises/practice/crypto-square/crypto_square_test.py
by adding this code to CryptoSquareTest class
```python
def test_empty_plaintext_after_normalized(self):
    value = "... --- ..."
    expected = ""
    self.assertEqual(cipher_text(value), expected)
```

**Comment by BethanyG** [comment]
Hi @izmirli 👋🏽 

Thanks for filing this issue, and for reading through other issues and documentation to get oriented. 💛 💙  _**You did the exact right thing!**_ - `Crypto Square` is indeed a practice exercise with a test generation template, so when adding test cases, it is best to open a PR in `problem-specifications`,  so that the new case(s) can be discussed cross-track.  The only exception would be a test case that is targeting a unique feature of Python where the case and data could not be shared with any other programming language.

Once the case(s) are approved in problem-specs and merged, they can be pulled down to individual tracks and incorporated.

Thanks again for being so contentious! 🎉

**Comment by izmirli** [comment]
Thanks @BethanyG for your kind words and for detailing the process with mention regarding the exception case.

Should this issue be kept open till new test case incorporated here? Or closed if there is no further use for it?

BTW, do you have permission for making an approving review for the PR in `problem-specifications`?

**Comment by BethanyG** [comment]
@izmirli -- Let's keep it open as a reminder to me to follow up on the issue in `problem-specs`.  I don't have time this morning to review the `problem specs` PR, but do hope to get to it by the end of my day today (I am in pacific time).

However, since `problem-specs` is a bit of a special repo, you'll need approvals from three track maintainers, as opposed to the one we require for an individual language track, so it may take a little while to get discussed and go through.

**Comment by izmirli** [comment]
@BethanyG -- Thanks for your good intentions! 
There is no rush, so only if and when you'll have free time.
BTW, there are already 2 approvals for the PR.

**Comment by BethanyG** [comment]
I just became the third approver.  I've also merged it in.  Thanks again for the PR!  ⭐ 🌈
