### ISSUE TITLE
[Cater Waiter] test for separate_appetizers function accepts a set in return statement 

### ISSUE THREAD

**Issue by list4c** [exercism/python#3190]
I was doing the task no. 6 'Pull out Appetizers for Passing on Trays' and found out that my result passes tests even though it's a set and not a list.

This is because the test uses the `sorted()` function which returns an object with `list` type. I think this is a bug, because the requirements said I should return a `list`.   
My idea of fixing the test is to use the method `sort()` instead of `sorted()`.

`self.assertEqual((separate_appetizers(item[0], item[1]).sort()), (result.sort()), msg=error_message)`

In this case my solution does not pass and I get the following error:
 
`AttributeError: 'set' object has no attribute 'sort'`

Which may probably be a bit confusing for someone checking test output, but maybe there is a way to catch this error and throw a custom message.

**Comment by BethanyG** [comment]
@list4c - That is an excellent catch!  **Thank you** for submitting this issue - and apologies for the extreme delay in getting back to you.  I've submitted a [PR to fix this](https://github.com/exercism/python/pull/3340).  I don't like having two assertions in the same test, but I think it might be cleaner to do that instead of doing a whole separate test just to check the return type.

I considered using `sort()`, but its harder to then trap the error and surface it as a test failure.

Please let me know if you have questions or issues.  Thanks again for reporting this.

**Comment by list4c** [comment]
Hi, cool!
Thanks, looks meaningful and will nicely warn users that they return an incorrect data structure.
