### ISSUE TITLE
Please update the Python version for the unit test checking

### ISSUE THREAD

**Issue by valof** [exercism/python#3198]
As you can see from the Python track in my Iteration #2 of the Space Age exercise, even though the solution was correct it has not been accepted. 
Apparently the version of Python you are using is having this problem not fixed. I checked that it is fixed at the latest version of Python.
This is my iteration: https://exercism.org/tracks/python/exercises/space-age/iterations
This is my discussion with Mentor: https://exercism.org/tracks/python/exercises/space-age/mentor_discussions/1d21741eb3c1443688340ad125fc2ef2
An example that recreates the problem even more clearly is attached.
[bug.zip](https://github.com/exercism/python/files/10000454/bug.zip)
If you tell me how to contribute to the Exercism I can upgrade the version 😆

**Comment by BethanyG** [comment]
Hi @valof 👋🏽 

Thanks for filing this issue.  Unfortunately, I am unable to view your solutions or mentor discussion from the links you have provided.  You'll need to provide the code & discussion in a code fence or via screengrabs.

 However, I do know that our track and tooling are on Python 3.10+, and that since Python 3.11 has only just gotten out of beta, we are not going to upgrade to it until well into next year.

I will not be downloading your `bug.zip` file, since I do not know what code the `.zip` contains, but if you can provide either links to a bug report against Python or Pytest or other sources describing the bug, I can look into it.

Beyond that, I would recommend bringing up the topic in our [discussion forum](https://forum.exercism.org/latest), to see if other mentors agree with the assessment of the bug, and also see if anyone has a workaround or suggestions on how to avoid it.

**Comment by valof** [comment]
Hi Bethany ✌
This is the code, it is trivial, I made a simplification to it.
As for bringing this topic to the forum, I can do it, but first I would like to ask if you agree that it is a bug (note, the behavior in 3.11 is as I expected it to be.)
Thanks!

```
list_tuples=[
    ('test1', 'result1'),
    ('test2','result2')
]

class Test:
    def _my_calc(self, x):
        return self.s+'_'+x
    def __init__(self, s, is_bug):
        self.s = s

        if is_bug:
            for p in list_tuples:
                setattr(self, 'on_'+p[0], lambda: self._my_calc(p[1]))
        else:
            setattr(self, 'on_test1', lambda: self._my_calc('result1'))
            setattr(self, 'on_test2', lambda: self._my_calc('result2'))

print ('This is working as expected:---------------------------')
print (Test('OK on test1:', False).on_test1())
print (Test('OK on test2:', False).on_test2())
print ('But this is not:--------------------------------------')
print (Test('OK on test2:', True).on_test2())
print (Test('WTF is wrong with test1?:', True).on_test1()) 
```

**Comment by BethanyG** [comment]
Given the result of the discussion, I am going to close this issue.  However, for future reference, I'll link the mentioned article:

[Late Binding Variables: It's a Trap!](https://medium.com/skiller-whale/late-binding-variables-its-a-trap-c17af980164f).

For one (_older, but really good_) dynamic programming strategy, I recommend [this community solution](https://exercism.org/tracks/python/exercises/space-age/solutions/smart-alek) , using a dictionary comprehension,  ` setattr`, and a `lambda` in a private function.  You can also use [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) to return a partial evaluation, as [this solution](https://exercism.org/tracks/python/exercises/space-age/solutions/Daniel-at-github) does.
