### ISSUE TITLE
Add  additional test case to 'Matching Brackets'

### ISSUE THREAD

**Issue by tolstovskiy** [exercism/python#3659]
I suggest  to add addtional test case to 'Matching Brackets' exersize. Something like this:
```
def test_new_pair_at_the_end(self) -> None:                                                                            
    self.assertEqual(is_paired("([]){}"), True)    
```
The reason is that i managed to pass all test with wrong solution:
```
OPENERS=('[','{','(')
CLOSERS=(']','}',')')
def is_paired(input_string):
    input_string_filtered=''.join(symbol for symbol in input_string if (symbol in OPENERS or symbol in CLOSERS))
    all_paired=True
    while input_string_filtered!='':
        if input_string_filtered[0] in OPENERS and len(input_string_filtered)%2==0:
            end_checker= CLOSERS.index(input_string_filtered[-1]) if input_string_filtered[-1] in CLOSERS else 4
            neighbor_checker=CLOSERS.index(input_string_filtered[1]) if input_string_filtered[1] in CLOSERS else 4
            if OPENERS.index(input_string_filtered[0])==neighbor_checker:
                input_string_filtered=input_string_filtered[2:]
            elif OPENERS.index(input_string_filtered[0])==end_checker:
                input_string_filtered=input_string_filtered[1:-1]
            else:
                all_paired=False
                break
        else: 
            all_paired=False  
            break
    return all_paired

```

**Comment by BethanyG** [comment]
Hi @tolstovskiy 👋🏽 

The tests for this exercise on the Python track are pulled from a cross-track repo called [problem-specficiations](https://github.com/exercism/problem-specifications/blob/main/exercises/matching-brackets/canonical-data.json).  

Unless this proposed test is to get at something that is specific to _Python_ (which it doesn't look like it is), you should propose the change for problem-specifications so that all language tracks can benefit.  Also, you should open a topic on the [forum](forum.exercsim.org) to discuss the problem-specifications change.  _**Thanks!**_.
