### ISSUE TITLE
I will implement simple-linked-list

### ISSUE THREAD

**Issue by laurauzcategui** [exercism/python#384]
Newbie in exercism :hand# would like a review on my 1st pull request: #383

**Comment by eliaahadi** [comment]
Was this implemented? I saw a double linked list, but not a simple one.

**Comment by m-a-ge** [comment]
There is https://github.com/exercism/python/tree/master/exercises/linked-list in https://github.com/exercism/python/tree/master/exercises

@eliaahadi, is there a point in implementing a simple one?

**Comment by eliaahadi** [comment]
Doubly linked list does cover simple one, that said for a beginner programmer, doubly is harder and to build skills progressively, simple linked list is easier to start with. If this is something that is easy to implement, then we can consider doing it. Otherwise, no need for this. Also, the name of linked list should be updated to "Doubly Linked List" instead of just "Linked List" since I was actively looking for just simple linked list. It's also on the page of unimplemented exercises.

**Comment by m-a-ge** [comment]
@eliaahadi, got it.
Do feel like implementing it?
