### ISSUE TITLE
Rework word-count exercise to be consistent

### ISSUE THREAD

**Issue by behrtam** [exercism/python#445]
In 2015 we decided to make the `word-count` exercise more interesting and not only split on white spaces (https://github.com/exercism/xpython/pull/177) which was inspired by the Haskell track. Since than other tracks where against it and so Haskell moved back to white space only (https://github.com/exercism/xhaskell/issues/501). This is also the way the canonical test data looks like. So maybe we should drop the python specialty to be more uniform.

**Comment by csabella** [comment]
As you said, it makes the exercise more interesting to split on more than white space.  Since it was an early exercise, I found it quite challenging to come up with a solution to do more than just split().  So, while it was an excellent exercise to learn from, it may be too early in the ordering (assuming that the exercises get progressively more difficult) to introduce both complicated splitting _and_ counting.  However, it was also not impossible to figure out a solution for, even with limited knowledge, so I like that it wasn't easy because I had learn more to solve it.   Maybe have this one with white space only and a later exercise for more complicated parsing/counting?  And maybe there's already an exercise for that?

**Comment by rootulp** [comment]
+1 for conforming to the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/word-count/canonical-data.json)

**Comment by cmccandless** [comment]
Closing as this was addressed in #1044.
