### ISSUE TITLE
Rework phone-numbers

### ISSUE THREAD

**Issue by behrtam** [exercism/python#471]
The canonical test data has been updated [(canonical-data.json)](https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json) but I think there is more work to be done than just adding the missing test cases.

### Invalid input

Right now invalid input is handled by returning `10 * "0"`. I think we should probably switch this to `Exceptions` instead.

### exercise extension

Right now we do some extra stuff like extracting the area code. While I kind of like it, we could also build the exercise down to only checking and formatting the hole number. Than it would make sense to switch from a class based solution to a functional one.

### member, property or getter
```python
number = Phone("123456789").number
self.assertEqual(number.area_code(), "123")
```
If we stick with the exercise extension (area code, exchange code, subscriber number) which is mentioned in the description but not part of the canonical test data, we should choose the same way of access for all of them.

**Comment by N-Parsons** [comment]
I've updated the tests cases in PR #529 because they were leading to a discrepancy between the README and the tests, and thus caused me some confusion when I was implementing my solution. The README said that the area and exchange codes must start with [2-9], but the tests were all using an area code starting with 1.

### Invalid input
I agree that raising an exception would be preferable to returning a string of zeros.

### Extension
Personally, I quite like the current extension with the class-based solution. In an application, it's reasonable to expect that you might want to be able to pull out the individual components of a number without having to get the whole number and slice it in the right way each time. This would be particularly useful way to implement it if an actual application was going to extended to handle more than just the NANP format and it thus required different slice sizes/positions.

I would be inclined to make them all properties, so that they are used in the same way as `Phone.number`. To me it makes the most sense, since `number` can be implemented as a property with the current tests to mask an alternative way of storing the phone number that makes `pretty` formatting cleaner to implement (my solution used a tuple containing the four parts).
