### ISSUE TITLE
complex-numbers: operator overloading

### ISSUE THREAD

**Issue by SaschaMann** [exercism/python#724]
The complex-number exercise testsuite and [example](https://github.com/lilislilit/python/blob/master/exercises/complex-numbers/example.py) use methods `add`, `mul` etc. instead of the operators `__add__`, `__mul__`. Using the latter, one could do `ComplexNumber(1, 2) + ComplexNumber(3, 4)` instead of `ComplexNumber(1, 2).add(ComplexNumber(3, 4))` which might be a more natural/pythonic way to write these. Perhaps changing it to the operator version would make this exercise a bit more interesting and applicable to "real life" use cases?

**Comment by m-a-ge** [comment]
@SaschaMann, good point, thanks! I totally agreed.

I will showcase use of Python`s magic methods an operator overloading (Java for example does not have such luxury) in action. Perhaps it would be a good idea to include a hint explaining what it is in the exercise as well

**Comment by cmccandless** [comment]
`__abs__()` can also be overridden.

**Comment by susg** [comment]
H, how do I override `abs` and `conjugate`? And in order to override `exp` it should renamed to `__pow__` and `div` to `__truediv__` if using python 3.3.

**Comment by cmccandless** [comment]
@susg Hi! If you are interested in working on this, please [create a pull request to claim the issue](https://github.com/exercism/python/blob/master/README.md#pull-requests).

There is no operator to override for `conjugate`, so that should remain a traditional method.

`exp` is actually different from `__pow__`. See [Wolfram Alpha's explanation of Complex Exponentiation](http://mathworld.wolfram.com/ComplexExponentiation.html) for more information.

For more info on overloading operators, see below:
* [Python 2](https://docs.python.org/2/library/operator.html)

* [Python 3](https://docs.python.org/3/library/operator.html)

@m-a-ge susg raised a good point; in Python 2, the operator for `/` is `__div__`, while in Python 3 it is `__truediv__`. Perhaps the template solution should contain both, with a note in the differences between the two? Having both will still interpret in either 2 or 3, so this would simply be covering all bases.

**Comment by cmccandless** [comment]
As this is no longer pending resolution of #1057, I am removing the pinned label.
