### ISSUE TITLE
add postfix_evaluation

### ISSUE THREAD

**Issue by tbhaxor** [exercism/python#923]
i am adding a directory postfix_evaluation

**Comment by m-a-ge** [comment]
Hm, I'm quite following what you mean.

Could you please clarify, @tbhaxor?

**Comment by tbhaxor** [comment]
@m-a-ge i am adding two file `example.py` and `postfix_evaluation.py` in _exercise/postfix_evaluation_

**Comment by m-a-ge** [comment]
@tbhaxor, first of all, thanks for your effort.
I would like to clarify a few things. There is a special repo https://github.com/exercism/problem-specifications where all exercises are defined, discussed their purpose, what tests should be used to evaluate learner's solution etc. So, I strongly suggest adding your exercise idea there first.
As for this track, you solution should work with both versions of Python, have a solid test suite and `README.md` should follow the certain format (see other exercises).

Have you used Exercism before?

**Comment by tbhaxor** [comment]
@m-a-ge no 😞

**Comment by m-a-ge** [comment]
@tbhaxor that's Ok.
I recommend to look at open issues - https://github.com/exercism/python/issues, choose something suitable, resolve it and then return to your initial PR. It'll give background you need.

Good starting point is to take any issue linked to #808. Be sure to check if they're no already open PRs for that issue

**Comment by N-Parsons** [comment]
I'm going to close this issue because the suggested exercise is not in the [exercism/problem-specifications](https://github.com/exercism/problem-specifications) and is very similar to `forth`. If you think that this exercise should be added, the best place to raise an issue or make a pull request is [exercism/problem-specifications](https://github.com/exercism/problem-specifications).
